In [1]:
import pandas as pd
import re

In [2]:
cat62 = pd.read_csv("data/cat-62.csv")

In [3]:

#cat62 = cat62[cat62["flightid"] != "Data final não disponível"]

In [4]:


cat62['dt_radar'] = pd.to_datetime(cat62['dt_radar'], unit='ms')

In [5]:
bimtra = pd.read_csv("data/bimtra2.csv")

In [6]:

bimtra['dt_dep'] = pd.to_datetime(bimtra['dt_dep'], unit='ms')
bimtra['dt_arr'] = pd.to_datetime(bimtra['dt_arr'], unit='ms')

In [7]:
bimtra["target"] = (bimtra["dt_arr"] - bimtra["dt_dep"]) // pd.Timedelta('1s')

In [8]:
bimtra["linha"] = bimtra["origem"] + bimtra["destino"]

In [9]:
bimtra = bimtra.drop_duplicates(subset='flightid')

In [10]:
bimtra = bimtra[bimtra["target"] > 1500]

In [11]:
bimtra

,flightid,origem,destino,dt_dep,dt_arr,target,linha
0,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ
1,c7c5c10716335b048f86d8c52fcba3f2,SBGR,SBRJ,2022-06-01 00:57:01,2022-06-01 01:32:53,2152,SBGRSBRJ
2,3162de7203a972f071d5a48e8f0f4828,SBBR,SBRJ,2022-06-01 00:26:52,2022-06-01 01:43:45,4613,SBBRSBRJ
3,8fcd243e9b9eebbe62ab145ce04b6ab5,SBKP,SBCF,2022-06-01 00:58:40,2022-06-01 01:41:41,2581,SBKPSBCF
4,504a62621cd231d6ab67e674ce538cd3,SBCF,SBFL,2022-06-01 01:00:38,2022-06-01 02:33:05,5547,SBCFSBFL
...,...,...,...,...,...,...,...
599819,492598a440f1e952c3768b8ce7febc1f,SBBR,SBSP,2023-05-13 14:48:29,2023-05-13 16:08:05,4776,SBBRSBSP
599820,766783c7267aead68c4c2452b0cd373f,SBPA,SBSP,2023-05-13 14:56:52,2023-05-13 16:12:14,4522,SBPASBSP
599821,5c00d263d1cfc37deb53b5a7b7a2be75,SBCT,SBSP,2023-05-13 15:37:45,2023-05-13 16:18:34,2449,SBCTSBSP
599822,64cedf597c56623e43c04bf4c16f9fa3,SBRJ,SBSP,2023-05-13 15:35:07,2023-05-13 16:23:51,2924,SBRJSBSP
599823,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT

In [12]:
cat62 = cat62.merge(bimtra, on="flightid", how="left")

In [13]:
cat62["linha"] = cat62["origem"] + cat62["destino"]

In [14]:
cat62.sort_values(by=['flightid', 'dt_radar'], inplace=True)

In [15]:
from math import radians, sin, cos, sqrt, atan2, degrees

def haversine(lat1, lon1, lat2, lon2):
    R = 6371.0  # raio da Terra em km

    lat1_rad = radians(lat1)
    lon1_rad = radians(lon1)
    lat2_rad = radians(lat2)
    lon2_rad = radians(lon2)

    dlon = lon2_rad - lon1_rad
    dlat = lat2_rad - lat1_rad

    a = sin(dlat / 2)**2 + cos(lat1_rad) * cos(lat2_rad) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [16]:


cat62["lat"] = cat62["lat"].apply(degrees)
cat62["lon"] = cat62["lon"].apply(degrees)

In [17]:
resumo_voo = cat62.groupby('flightid').agg({
    'dt_radar': lambda x: (x.max() - x.min()).total_seconds(),
    'lat': ['first', 'last'],
    'lon': ['first', 'last'],
    'flightlevel': ['mean', 'min', 'max', 'std'],
    'speed': ['mean', 'min', 'max', 'std'],
    'linha': 'first'
})

In [18]:
resumo_voo['distancia'] = resumo_voo.apply(lambda row: haversine(row[('lat', 'first')], row[('lon', 'first')], 
                                                           row[('lat', 'last')], row[('lon', 'last')]), axis=1)

In [19]:
# Aplicar a função join às colunas do DataFrame
resumo_voo.reset_index(inplace=True)

In [20]:
resumo_voo

                                flightid dt_radar        lat             \
                                         <lambda>      first       last
0       0000f76a51b99be3f181ea2b201b34ef   6543.0 -12.898787 -22.453113
1       00010bb2c49076d56a9815122fefc8aa   4083.0 -19.644736 -23.626155
2       00010ed6d09c78b5a37f4df13f524f56   7740.0 -13.035493 -23.623237
3       000143522a56fa245543e477c74fd908  10019.0 -23.609967  -8.135660
4       00014fa436546dfdc7a67919e9e1ea47   4924.0 -19.641217 -27.365809
...                                  ...      ...        ...        ...
278094  fffeba6342187a9ee0caff2526e4ff0e   4563.0 -23.578866 -29.996528
278095  ffff413d10cfbb298a9411855e80a0f0   6602.0 -22.874854 -29.994711
278096  ffff62189abb326d9f18ff1412e5de8e   3782.0 -19.630710 -23.437804
278097  ffffd0e5ce497de7ddf3d34d19b9ce3a   2581.0 -23.590285 -22.939142
278098  ffffd4331f8b78c6e726eda4e6a2f5ac   9482.0 -23.415394  -8.125157

              lon            flightlevel                                speed  \
            first       last        mean   min    max         std        mean
0      -38.277699 -46.233340  308.194737  14.0  340.0   70.927036  409.636842
1      -43.958119 -46.656405  214.356522  25.0  360.0  115.735496  312.017391
2      -38.282166 -46.658587  318.598086  24.0  380.0  106.012886  389.071770
3      -46.567788 -34.923127  298.994382   1.0  370.0  118.987703  416.511236
4      -43.961015 -48.217413  281.933824  26.0  360.0  100.075024  393.022059
...           ...        ...         ...   ...    ...         ...         ...
278094 -46.689515 -51.181826  263.000000   1.0  380.0  129.199031  364.925926
278095 -43.126958 -51.177427  305.910995   5.0  380.0  117.219396  335.778351
278096 -43.970909 -46.493859  187.427273  26.0  360.0  126.294796  317.663636
278097 -46.671998 -43.155191  144.435897   3.0  270.0   93.353620  307.051282
278098 -46.426775 -34.923833  318.339161   1.0  371.0  102.369508  433.730769

                                    linha    distancia
          min    max        std     first
0       170.0  440.0  42.689970  SBSVSBGR  1355.300518
1       106.0  424.0  94.817274  SBCFSBSP   523.193228
2       145.0  436.0  58.582779  SBSVSBSP  1471.285722
3       123.0  477.0  83.686207  SBSPSBRF  2121.248922
4       142.0  449.0  63.645601  SBCFSBFL   962.125338
...       ...    ...        ...       ...          ...
278094  122.0  433.0  79.087701  SBSPSBPA   841.245187
278095  110.0  419.0  58.055247  SBRJSBPA  1125.897592
278096  142.0  421.0  92.550435  SBCFSBGR   497.260753
278097  120.0  372.0  73.091812  SBSPSBRJ   366.466603
278098  131.0  492.0  73.327965  SBGRSBRF  2096.255597

[278099 rows x 16 columns]

In [21]:
resumo_voo = resumo_voo.T.reset_index().T

In [22]:
arr = []
for i in range(0, len(resumo_voo.iloc[0].values)):
    arr.append(resumo_voo.iloc[0].values[i] + "_" + resumo_voo.iloc[1].values[i])

In [23]:
resumo_voo = resumo_voo.rename(columns=dict(zip(resumo_voo.columns, arr)))

In [24]:
resumo_voo = resumo_voo.iloc[2:]

In [25]:
resumo = resumo_voo.groupby('linha_first').agg({
    'flightid_': 'count',
    'dt_radar_<lambda>': ['mean', 'min', 'max', 'std'],
    'flightlevel_mean': 'mean',
    'flightlevel_max': 'mean',
    'distancia_': 'mean',
    'flightlevel_std': ['std', 'mean'],
    'speed_std': ['mean','std']
})

# Exibir o resumo
print(resumo)

            flightid_ dt_radar_<lambda>                                \
                count              mean     min      max          std
linha_first
SBBRSBCF         2864        3209.02095     0.0   8277.0   505.178107
SBBRSBCT         1026       5533.775828     4.0   8166.0   566.988127
SBBRSBFL          336         6625.3125     4.0  14041.0   802.059104
SBBRSBGL          693       4503.103896   362.0   7138.0   523.815262
SBBRSBGR         3395       4384.605007     4.0  15064.0   654.196770
...               ...               ...     ...      ...          ...
SBSVSBKP         1494       7367.996653   121.0  12302.0   761.483020
SBSVSBPA           79      11771.683544  1683.0  13623.0  1455.223285
SBSVSBRF         1628       3782.278256     0.0   9182.0   518.334080
SBSVSBRJ         1810       6713.546409   843.0  10924.0   610.718029
SBSVSBSP         3866       7808.403777   305.0  22083.0   970.685786

            flightlevel_mean flightlevel_max   distancia_ flightlevel_std  \
                        mean            mean         mean             std
linha_first
SBBRSBCF          223.140032      352.609637   575.834702       15.761247
SBBRSBCT          281.163088      368.132554  1063.467771       12.570011
SBBRSBFL          292.218861      371.767857  1284.169505       14.999555
SBBRSBGL          259.707834      368.138528   887.504293       13.093562
SBBRSBGR          264.201495      366.849485   823.354395       16.848180
...                      ...             ...          ...             ...
SBSVSBKP          305.560135      369.228916  1426.424275       17.322919
SBSVSBPA          324.435099      375.189873  2277.382502        8.228249
SBSVSBRF          226.595839      362.367322   643.423234       15.844889
SBSVSBRJ          291.883159      378.577901  1226.672791       12.480558
SBSVSBSP          303.340569      369.553802  1453.162029       17.806880

                         speed_std
                   mean       mean        std
linha_first
SBBRSBCF       113.0122  96.347326  16.596938
SBBRSBCT     113.725753  84.117677  13.205417
SBBRSBFL       115.9371  78.886886  13.861260
SBBRSBGL     122.238626   92.58519  15.665866
SBBRSBGR     112.524767  84.637091  18.227339
...                 ...        ...        ...
SBSVSBKP     102.058405  68.243716  16.668225
SBSVSBPA      99.879211  62.362856   8.362796
SBSVSBRF     127.225242  97.002481  14.503896
SBSVSBRJ     124.123994  82.783449  13.068024
SBSVSBSP     103.473904  69.357163  17.566394

[136 rows x 12 columns]

In [26]:
resumo.reset_index(inplace=True)
resumo.to_csv("data/resumo_voo.csv", index=False)

In [27]:
import pandas as pd
resumo = pd.read_csv("data/resumo_voo.csv")
resumo

,linha_first,flightid_,dt_radar_<lambda>,dt_radar_<lambda>.1,dt_radar_<lambda>.2,dt_radar_<lambda>.3,flightlevel_mean,flightlevel_max,distancia_,flightlevel_std,flightlevel_std.1,speed_std,speed_std.1
0,NaN,count,mean,min,max,std,mean,mean,mean,std,mean,mean,std
1,SBBRSBCF,2864,3209.0209497206706,0.0,8277.0,505.1781074764571,223.1400324508525,352.60963687150837,575.834701784026,15.761247114997513,113.01220021738615,96.34732592058592,16.596938295458155
2,SBBRSBCT,1026,5533.775828460039,4.0,8166.0,566.9881268946964,281.1630883931095,368.1325536062378,1063.4677710301346,12.570011323594358,113.72575327754934,84.1176769694231,13.2054169916998
3,SBBRSBFL,336,6625.3125,4.0,14041.0,802.0591041375009,292.2188612817781,371.76785714285717,1284.1695049641773,14.999555259971018,115.93710014539403,78.8868858421317,13.861260443979065
4,SBBRSBGL,693,4503.103896103896,362.0,7138.0,523.8152618016763,259.70783363369543,368.13852813852816,887.5042925637619,13.09356154145346,122.23862626914057,92.58519039880454,15.665866076042905
...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,SBSVSBKP,1494,7367.996653279786,121.0,12302.0,761.483020478947,305.5601352677385,369.2289156626506,1426.4242748944434,17.322919144273627,102.05840475491932,68.243716105359,16.668224626368342
133,SBSVSBPA,79,11771.683544303798,1683.0,13623.0,1455.2232848701617,324.43509942690906,375.1898734177215,2277.3825023041554,8.22824879734405,99.87921093160097,62.36285594137942,8.362795726130804
134,SBSVSBRF,1628,3782.2782555282556,0.0,9182.0,518.3340796845335,226.5958387344471,362.3673218673219,643.4232339847347,15.844889254045219,127.2252417382822,97.0024814261082,14.503895888882802
135,SBSVSBRJ,1810,6713.546408839779,843.0,10924.0,610.7180291362184,291.8831591581199,378.5779005524862,1226.6727911976184,12.48055842996475,124.12399364375192,82.78344889091554,13.068023636248327
136,SBSVSBSP,3866,7808.403776513192,305.0,22083.0,970.6857858639729,303.3405694075722,369.55380237972065,1453.1620287057992,17.806879818186644,103.47390427123766,69.3571629501052,17.56639419188513

In [28]:
resumo

,linha_first,flightid_,dt_radar_<lambda>,dt_radar_<lambda>.1,dt_radar_<lambda>.2,dt_radar_<lambda>.3,flightlevel_mean,flightlevel_max,distancia_,flightlevel_std,flightlevel_std.1,speed_std,speed_std.1
0,NaN,count,mean,min,max,std,mean,mean,mean,std,mean,mean,std
1,SBBRSBCF,2864,3209.0209497206706,0.0,8277.0,505.1781074764571,223.1400324508525,352.60963687150837,575.834701784026,15.761247114997513,113.01220021738615,96.34732592058592,16.596938295458155
2,SBBRSBCT,1026,5533.775828460039,4.0,8166.0,566.9881268946964,281.1630883931095,368.1325536062378,1063.4677710301346,12.570011323594358,113.72575327754934,84.1176769694231,13.2054169916998
3,SBBRSBFL,336,6625.3125,4.0,14041.0,802.0591041375009,292.2188612817781,371.76785714285717,1284.1695049641773,14.999555259971018,115.93710014539403,78.8868858421317,13.861260443979065
4,SBBRSBGL,693,4503.103896103896,362.0,7138.0,523.8152618016763,259.70783363369543,368.13852813852816,887.5042925637619,13.09356154145346,122.23862626914057,92.58519039880454,15.665866076042905
...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,SBSVSBKP,1494,7367.996653279786,121.0,12302.0,761.483020478947,305.5601352677385,369.2289156626506,1426.4242748944434,17.322919144273627,102.05840475491932,68.243716105359,16.668224626368342
133,SBSVSBPA,79,11771.683544303798,1683.0,13623.0,1455.2232848701617,324.43509942690906,375.1898734177215,2277.3825023041554,8.22824879734405,99.87921093160097,62.36285594137942,8.362795726130804
134,SBSVSBRF,1628,3782.2782555282556,0.0,9182.0,518.3340796845335,226.5958387344471,362.3673218673219,643.4232339847347,15.844889254045219,127.2252417382822,97.0024814261082,14.503895888882802
135,SBSVSBRJ,1810,6713.546408839779,843.0,10924.0,610.7180291362184,291.8831591581199,378.5779005524862,1226.6727911976184,12.48055842996475,124.12399364375192,82.78344889091554,13.068023636248327
136,SBSVSBSP,3866,7808.403776513192,305.0,22083.0,970.6857858639729,303.3405694075722,369.55380237972065,1453.1620287057992,17.806879818186644,103.47390427123766,69.3571629501052,17.56639419188513

In [29]:
import pandas as pd
esperas = pd.read_csv("data/esperas.csv")
esperas["dt_dep"] = pd.to_datetime(esperas["hora"], unit='ms')
esperas["hora"] = pd.to_datetime(esperas["hora"], unit='ms')
esperas["diaSemana"] = esperas["hora"].dt.dayofweek

esperas["hora"] = esperas["hora"].dt.hour

In [30]:
esperas_hora = esperas.groupby(["aero", "hora"]).agg({"esperas": ["mean", "sum"]})
esperas_semana = esperas.groupby(["aero", "diaSemana"]).agg({"esperas": ["mean", "sum"]})

In [31]:

esperas_aero = esperas.groupby(["aero"]).agg({"esperas": ["mean", "sum"]})

In [32]:
esperas

       esperas  hora  aero              dt_dep  diaSemana
0            0     0  SBBR 2022-06-01 00:00:00          2
1            0     1  SBBR 2022-06-01 01:00:00          2
2            0     2  SBBR 2022-06-01 02:00:00          2
3            0     3  SBBR 2022-06-01 03:00:00          2
4            0     4  SBBR 2022-06-01 04:00:00          2
...        ...   ...   ...                 ...        ...
93307        0    19  SBSV 2023-04-15 19:00:00          5
93308        0    20  SBSV 2023-04-15 20:00:00          5
93309        0    21  SBSV 2023-04-15 21:00:00          5
93310        0    22  SBSV 2023-04-15 22:00:00          5
93311        0    23  SBSV 2023-04-15 23:00:00          5

[93312 rows x 5 columns]

In [33]:
bimtra["diaSemana"] = bimtra["dt_dep"].dt.dayofweek

bimtra["hora"] = bimtra["dt_dep"].dt.hour

In [34]:
bimtra['HoraDataDest'] = bimtra['dt_arr'].dt.strftime('%Y-%m-%d %H')

In [35]:
#esperas.to_csv("data/esperas_join.csv", index=False)

In [36]:
bimtra['HoraData'] = bimtra['dt_dep'].dt.strftime('%Y-%m-%d %H')
esperas['HoraData'] = esperas['dt_dep'].dt.strftime('%Y-%m-%d %H')

# Mesclar os dataframes usando a coluna "HoraData"
df_merge = pd.merge(bimtra, esperas, on='HoraData', how='left')

# Preencher NaN na coluna de espera com 0 (sem espera)
df_merge['esperas'] = df_merge['esperas'].fillna(0)
df_merge = df_merge.groupby("flightid").agg({"esperas": "sum"})
bimtra = bimtra.merge(df_merge.reset_index(), on="flightid", how="left")

In [37]:
bimtra

,flightid,origem,destino,dt_dep,dt_arr,target,linha,diaSemana,hora,HoraDataDest,HoraData,esperas
0,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ,2,0,2022-06-01 01,2022-06-01 00,0.0
1,c7c5c10716335b048f86d8c52fcba3f2,SBGR,SBRJ,2022-06-01 00:57:01,2022-06-01 01:32:53,2152,SBGRSBRJ,2,0,2022-06-01 01,2022-06-01 00,0.0
2,3162de7203a972f071d5a48e8f0f4828,SBBR,SBRJ,2022-06-01 00:26:52,2022-06-01 01:43:45,4613,SBBRSBRJ,2,0,2022-06-01 01,2022-06-01 00,0.0
3,8fcd243e9b9eebbe62ab145ce04b6ab5,SBKP,SBCF,2022-06-01 00:58:40,2022-06-01 01:41:41,2581,SBKPSBCF,2,0,2022-06-01 01,2022-06-01 00,0.0
4,504a62621cd231d6ab67e674ce538cd3,SBCF,SBFL,2022-06-01 01:00:38,2022-06-01 02:33:05,5547,SBCFSBFL,2,1,2022-06-01 02,2022-06-01 01,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
286075,492598a440f1e952c3768b8ce7febc1f,SBBR,SBSP,2023-05-13 14:48:29,2023-05-13 16:08:05,4776,SBBRSBSP,5,14,2023-05-13 16,2023-05-13 14,0.0
286076,766783c7267aead68c4c2452b0cd373f,SBPA,SBSP,2023-05-13 14:56:52,2023-05-13 16:12:14,4522,SBPASBSP,5,14,2023-05-13 16,2023-05-13 14,0.0
286077,5c00d263d1cfc37deb53b5a7b7a2be75,SBCT,SBSP,2023-05-13 15:37:45,2023-05-13 16:18:34,2449,SBCTSBSP,5,15,2023-05-13 16,2023-05-13 15,0.0
286078,64cedf597c56623e43c04bf4c16f9fa3,SBRJ,SBSP,2023-05-13 15:35:07,2023-05-13 16:23:51,2924,SBRJSBSP,5,15,2023-05-13 16,2023-05-13 15,0.0
286079,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT,5,16,2023-05-13 17,2023-05-13 16,0.0

In [38]:
bimtra.merge(esperas, left_on=["origem", "hora", "diaSemana"], right_on=["aero", "hora", "diaSemana"], how="left")

,flightid,origem,destino,dt_dep_x,dt_arr,target,linha,diaSemana,hora,HoraDataDest,HoraData_x,esperas_x,esperas_y,aero,dt_dep_y,HoraData_y
0,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ,2,0,2022-06-01 01,2022-06-01 00,0.0,0,SBKP,2022-06-01 00:00:00,2022-06-01 00
1,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ,2,0,2022-06-01 01,2022-06-01 00,0.0,0,SBKP,2022-06-08 00:00:00,2022-06-08 00
2,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ,2,0,2022-06-01 01,2022-06-01 00,0.0,0,SBKP,2022-06-15 00:00:00,2022-06-15 00
3,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ,2,0,2022-06-01 01,2022-06-01 00,0.0,0,SBKP,2022-06-22 00:00:00,2022-06-22 00
4,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ,2,0,2022-06-01 01,2022-06-01 00,0.0,0,SBKP,2022-06-29 00:00:00,2022-06-29 00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13247627,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT,5,16,2023-05-13 17,2023-05-13 16,0.0,0,SBPA,2023-03-18 16:00:00,2023-03-18 16
13247628,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT,5,16,2023-05-13 17,2023-05-13 16,0.0,0,SBPA,2023-03-25 16:00:00,2023-03-25 16
13247629,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT,5,16,2023-05-13 17,2023-05-13 16,0.0,0,SBPA,2023-04-01 16:00:00,2023-04-01 16
13247630,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT,5,16,2023-05-13 17,2023-05-13 16,0.0,0,SBPA,2023-04-08 16:00:00,2023-04-08 16
13247631,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT,5,16,2023-05-13 17,2023-05-13 16,0.0,0,SBPA,2023-04-15 16:00:00,2023-04-15 16

In [39]:
esperas_hora.columns = esperas_hora.columns.droplevel(0)

In [40]:
esperas_hora.reset_index(inplace=True)

In [41]:
esperas_semana.columns = esperas_semana.columns.droplevel(0)
esperas_semana.reset_index(inplace=True)

In [42]:
esperas_aero.columns = esperas_aero.columns.droplevel(0)
esperas_aero.reset_index(inplace=True)

In [43]:
esperas_semana

    aero  diaSemana      mean  sum
0   SBBR          0  0.009058   10
1   SBBR          1  0.019022   21
2   SBBR          2  0.034420   38
3   SBBR          3  0.022163   25
4   SBBR          4  0.069149   78
..   ...        ...       ...  ...
79  SBSV          2  0.011775   13
80  SBSV          3  0.015071   17
81  SBSV          4  0.006206    7
82  SBSV          5  0.003623    4
83  SBSV          6  0.009964   11

[84 rows x 4 columns]

In [44]:
esperas_hora.to_csv("data/esperas_hora.csv", index=False)
esperas_semana.to_csv("data/esperas_semana.csv", index=False)

In [45]:
bimtra = bimtra.merge(esperas_hora, right_on=["aero", "hora"], left_on=["origem", "hora"] , how="left")
bimtra = bimtra.merge(esperas_semana, right_on=["aero", "diaSemana"], left_on=["origem", "diaSemana"] , how="left")

In [46]:
esperas_aero.to_csv("data/esperas_aero.csv", index=False)

In [47]:
bimtra = bimtra.merge(esperas_aero, right_on=["aero"], left_on=["origem"] , how="left")

In [48]:
bimtra["origem"].unique()

array(['SBKP', 'SBGR', 'SBBR', 'SBCF', 'SBSP', 'SBRJ', 'SBFL', 'SBCT',
       'SBRF', 'SBPA', 'SBSV', 'SBGL'], dtype=object)

In [49]:
bimtra

,flightid,origem,destino,dt_dep,dt_arr,target,linha,diaSemana,hora,HoraDataDest,...,esperas,aero_x,mean_x,sum_x,aero_y,mean_y,sum_y,aero,mean,sum
0,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ,2,0,2022-06-01 01,...,0.0,SBKP,0.694444,225,SBKP,0.221014,244,SBKP,0.191872,1492
1,c7c5c10716335b048f86d8c52fcba3f2,SBGR,SBRJ,2022-06-01 00:57:01,2022-06-01 01:32:53,2152,SBGRSBRJ,2,0,2022-06-01 01,...,0.0,SBGR,0.987654,320,SBGR,0.254529,281,SBGR,0.255401,1986
2,3162de7203a972f071d5a48e8f0f4828,SBBR,SBRJ,2022-06-01 00:26:52,2022-06-01 01:43:45,4613,SBBRSBRJ,2,0,2022-06-01 01,...,0.0,SBBR,0.000000,0,SBBR,0.034420,38,SBBR,0.024434,190
3,8fcd243e9b9eebbe62ab145ce04b6ab5,SBKP,SBCF,2022-06-01 00:58:40,2022-06-01 01:41:41,2581,SBKPSBCF,2,0,2022-06-01 01,...,0.0,SBKP,0.694444,225,SBKP,0.221014,244,SBKP,0.191872,1492
4,504a62621cd231d6ab67e674ce538cd3,SBCF,SBFL,2022-06-01 01:00:38,2022-06-01 02:33:05,5547,SBCFSBFL,2,1,2022-06-01 02,...,1.0,SBCF,0.055556,18,SBCF,0.173007,191,SBCF,0.150463,1170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286075,492598a440f1e952c3768b8ce7febc1f,SBBR,SBSP,2023-05-13 14:48:29,2023-05-13 16:08:05,4776,SBBRSBSP,5,14,2023-05-13 16,...,0.0,SBBR,0.015432,5,SBBR,0.004529,5,SBBR,0.024434,190
286076,766783c7267aead68c4c2452b0cd373f,SBPA,SBSP,2023-05-13 14:56:52,2023-05-13 16:12:14,4522,SBPASBSP,5,14,2023-05-13 16,...,0.0,SBPA,0.027778,9,SBPA,0.015399,17,SBPA,0.018904,147
286077,5c00d263d1cfc37deb53b5a7b7a2be75,SBCT,SBSP,2023-05-13 15:37:45,2023-05-13 16:18:34,2449,SBCTSBSP,5,15,2023-05-13 16,...,0.0,SBCT,0.046296,15,SBCT,0.022645,25,SBCT,0.037809,294
286078,64cedf597c56623e43c04bf4c16f9fa3,SBRJ,SBSP,2023-05-13 15:35:07,2023-05-13 16:23:51,2924,SBRJSBSP,5,15,2023-05-13 16,...,0.0,SBRJ,0.243827,79,SBRJ,0.160326,177,SBRJ,0.256816,1997
286079,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT,5,16,2023-05-13 17,...,0.0,SBPA,0.003086,1,SBPA,0.015399,17,SBPA,0.018904,147

In [50]:
#import pandas as pd
metar = pd.read_csv("data/metar.csv")

In [51]:
metar

                hora                                              metar  aero
0      1654041600000      METAR SBBR 010000Z 07002KT CAVOK 21/08 Q1018=  SBBR
1      1654045200000      METAR SBBR 010100Z 10002KT CAVOK 20/09 Q1019=  SBBR
2      1654048800000      METAR SBBR 010200Z 00000KT CAVOK 16/09 Q1019=  SBBR
3      1654052400000      METAR SBBR 010300Z 27002KT CAVOK 16/09 Q1019=  SBBR
4      1654056000000      METAR SBBR 010400Z 00000KT CAVOK 14/09 Q1018=  SBBR
...              ...                                                ...   ...
99617  1681585200000  METAR SBSV 151900Z 08008KT 050V110 9999 FEW030...  SBSV
99618  1681588800000  METAR SBSV 152000Z 09007KT 060V120 CAVOK 29/23...  SBSV
99619  1681592400000      METAR SBSV 152100Z 08007KT CAVOK 28/22 Q1011=  SBSV
99620  1681596000000      METAR SBSV 152200Z 08007KT CAVOK 28/22 Q1011=  SBSV
99621  1681599600000      METAR SBSV 152300Z 07008KT CAVOK 27/23 Q1012=  SBSV

[99622 rows x 3 columns]

In [52]:
import pandas as pd
from metar.Metar import Metar

# Função para parsear METAR
def parse_metar(metar):
    metar = metar.replace('METAF', 'METAR') 
    try:
        metar_obj = Metar(metar)
        temperature = metar_obj.temp.value() if metar_obj.temp else None
        dewpoint = metar_obj.dewpt.value() if metar_obj.dewpt else None
        wind_speed = metar_obj.wind_speed.value() if metar_obj.wind_speed else None
        wind_direction = metar_obj.wind_dir.value() if metar_obj.wind_dir else None
        visibility = metar_obj.vis.value() if metar_obj.vis else None
        pressure = metar_obj.press.value() if metar_obj.press else None
        weather = ', '.join([str(c) for c in metar_obj.weather]) if metar_obj.weather else None
        sky = ', '.join([str(c) for c in metar_obj.sky]) if metar_obj.sky else None
        return pd.Series([temperature, dewpoint, wind_speed, wind_direction, visibility, pressure, weather, sky])
    except Exception as e:
        #print(str(e))
        return pd.Series([None, None, None, None, None, None, None, None])

# Aplicar parse sobre METAR para cada linha
metar[['Temperatura', 'Ponto de Orvalho', 'Velocidade do Vento', 'Direção do Vento', 'Visibilidade', 'Pressão', 'Tempo', 'Céu']] = metar['metar'].apply(parse_metar)

/tmp/ipykernel_573279/1735850452.py:23: FutureWarning: Returning a DataFrame from Series.apply when the supplied function returns a Series is deprecated and will be removed in a future version.
  metar[['Temperatura', 'Ponto de Orvalho', 'Velocidade do Vento', 'Direção do Vento', 'Visibilidade', 'Pressão', 'Tempo', 'Céu']] = metar['metar'].apply(parse_metar)

In [53]:
metar

,hora,metar,aero,Temperatura,Ponto de Orvalho,Velocidade do Vento,Direção do Vento,Visibilidade,Pressão,Tempo,Céu
0,1654041600000,METAR SBBR 010000Z 07002KT CAVOK 21/08 Q1018=,SBBR,21.0,8.0,2.0,70.0,10000.0,1018.0,NaN,NaN
1,1654045200000,METAR SBBR 010100Z 10002KT CAVOK 20/09 Q1019=,SBBR,20.0,9.0,2.0,100.0,10000.0,1019.0,NaN,NaN
2,1654048800000,METAR SBBR 010200Z 00000KT CAVOK 16/09 Q1019=,SBBR,16.0,9.0,0.0,0.0,10000.0,1019.0,NaN,NaN
3,1654052400000,METAR SBBR 010300Z 27002KT CAVOK 16/09 Q1019=,SBBR,16.0,9.0,2.0,270.0,10000.0,1019.0,NaN,NaN
4,1654056000000,METAR SBBR 010400Z 00000KT CAVOK 14/09 Q1018=,SBBR,14.0,9.0,0.0,0.0,10000.0,1018.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
99617,1681585200000,METAR SBSV 151900Z 08008KT 050V110 9999 FEW030...,SBSV,29.0,23.0,8.0,80.0,10000.0,1011.0,None,"('FEW', <metar.Datatypes.distance object at 0x..."
99618,1681588800000,METAR SBSV 152000Z 09007KT 060V120 CAVOK 29/23...,SBSV,29.0,23.0,7.0,90.0,10000.0,1011.0,None,NaN
99619,1681592400000,METAR SBSV 152100Z 08007KT CAVOK 28/22 Q1011=,SBSV,28.0,22.0,7.0,80.0,10000.0,1011.0,None,NaN
99620,1681596000000,METAR SBSV 152200Z 08007KT CAVOK 28/22 Q1011=,SBSV,28.0,22.0,7.0,80.0,10000.0,1011.0,None,NaN
99621,1681599600000,METAR SBSV 152300Z 07008KT CAVOK 27/23 Q1012=,SBSV,27.0,23.0,8.0,70.0,10000.0,1012.0,None,NaN

In [54]:
metar.iloc[0]["metar"]

'METAR SBBR 010000Z 07002KT CAVOK 21/08 Q1018='

In [55]:

metar['HoraData'] = pd.to_datetime(metar['hora'], unit='ms').dt.strftime('%Y-%m-%d %H')
# Mesclar os dataframes usando a coluna "HoraData"



# Preencher NaN na coluna de espera com 0 (sem espera)

In [56]:
del bimtra["aero"]

In [57]:
# Agrupando por flight_id
df_merge = pd.merge(bimtra, metar, left_on=['destino', 'HoraDataDest'], right_on=['aero', 'HoraData'], how='left')

grouped_df = df_merge.groupby('flightid')

# Calculando as estatísticas
stats_df = grouped_df.agg({
    'Temperatura': ['mean', 'min', 'max', 'std'],
    'Ponto de Orvalho': ['mean', 'min', 'max', 'std'],
    'Velocidade do Vento': ['mean', 'min', 'max', 'std'],
    'Direção do Vento': ['mean', 'min', 'max', 'std'],
    'Visibilidade': ['mean', 'min', 'max', 'std'],
    'Pressão': ['mean', 'min', 'max', 'std']
})
stats_df.reset_index(inplace=True)
stats_df.columns = [''.join(col) for col in stats_df.columns]
bimtra = bimtra.merge(stats_df, on="flightid", how="left")

In [58]:
bimtra

,flightid,origem,destino,dt_dep,dt_arr,target,linha,diaSemana,hora,HoraDataDest,...,Direção do Ventomax,Direção do Ventostd,Visibilidademean,Visibilidademin,Visibilidademax,Visibilidadestd,Pressãomean,Pressãomin,Pressãomax,Pressãostd
0,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ,2,0,2022-06-01 01,...,150.0,NaN,10000.0,10000.0,10000.0,NaN,1015.0,1015.0,1015.0,NaN
1,c7c5c10716335b048f86d8c52fcba3f2,SBGR,SBRJ,2022-06-01 00:57:01,2022-06-01 01:32:53,2152,SBGRSBRJ,2,0,2022-06-01 01,...,150.0,NaN,10000.0,10000.0,10000.0,NaN,1015.0,1015.0,1015.0,NaN
2,3162de7203a972f071d5a48e8f0f4828,SBBR,SBRJ,2022-06-01 00:26:52,2022-06-01 01:43:45,4613,SBBRSBRJ,2,0,2022-06-01 01,...,150.0,NaN,10000.0,10000.0,10000.0,NaN,1015.0,1015.0,1015.0,NaN
3,8fcd243e9b9eebbe62ab145ce04b6ab5,SBKP,SBCF,2022-06-01 00:58:40,2022-06-01 01:41:41,2581,SBKPSBCF,2,0,2022-06-01 01,...,100.0,NaN,10000.0,10000.0,10000.0,NaN,1018.0,1018.0,1018.0,NaN
4,504a62621cd231d6ab67e674ce538cd3,SBCF,SBFL,2022-06-01 01:00:38,2022-06-01 02:33:05,5547,SBCFSBFL,2,1,2022-06-01 02,...,210.0,NaN,10000.0,10000.0,10000.0,NaN,1020.0,1020.0,1020.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286075,492598a440f1e952c3768b8ce7febc1f,SBBR,SBSP,2023-05-13 14:48:29,2023-05-13 16:08:05,4776,SBBRSBSP,5,14,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286076,766783c7267aead68c4c2452b0cd373f,SBPA,SBSP,2023-05-13 14:56:52,2023-05-13 16:12:14,4522,SBPASBSP,5,14,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286077,5c00d263d1cfc37deb53b5a7b7a2be75,SBCT,SBSP,2023-05-13 15:37:45,2023-05-13 16:18:34,2449,SBCTSBSP,5,15,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286078,64cedf597c56623e43c04bf4c16f9fa3,SBRJ,SBSP,2023-05-13 15:35:07,2023-05-13 16:23:51,2924,SBRJSBSP,5,15,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286079,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT,5,16,2023-05-13 17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
import pandas as pd

metaf = pd.read_csv("data/metaf.csv")
metaf['metaf'].apply(parse_metar)
metaf['metaf'] = metaf['metaf'].apply(lambda x: ' '.join(x.split()))

metaf[['Temperatura', 'Ponto de Orvalho', 'Velocidade do Vento', 'Direção do Vento', 'Visibilidade', 'Pressão', 'Tempo', 'Céu']] = metaf['metaf'].apply(parse_metar)

metaf['HoraData'] = pd.to_datetime(metaf['hora'], unit='ms').dt.strftime('%Y-%m-%d %H')
# Mesclar os dataframes usando a coluna "HoraData"

/tmp/ipykernel_573279/2430131428.py:4: FutureWarning: Returning a DataFrame from Series.apply when the supplied function returns a Series is deprecated and will be removed in a future version.
  metaf['metaf'].apply(parse_metar)
/tmp/ipykernel_573279/2430131428.py:7: FutureWarning: Returning a DataFrame from Series.apply when the supplied function returns a Series is deprecated and will be removed in a future version.
  metaf[['Temperatura', 'Ponto de Orvalho', 'Velocidade do Vento', 'Direção do Vento', 'Visibilidade', 'Pressão', 'Tempo', 'Céu']] = metaf['metaf'].apply(parse_metar)

In [60]:

df_merge = pd.merge(bimtra, metaf, left_on=['destino', 'HoraDataDest'], right_on=['aero', 'HoraData'], how='left')
# Agrupando por flight_id
grouped_df = df_merge.groupby('flightid')

# Calculando as estatísticas
stats_df = grouped_df.agg({
    'Temperatura': ['mean', 'min', 'max', 'std'],
    'Ponto de Orvalho': ['mean', 'min', 'max', 'std'],
    'Velocidade do Vento': ['mean', 'min', 'max', 'std'],
    'Direção do Vento': ['mean', 'min', 'max', 'std'],
    'Visibilidade': ['mean', 'min', 'max', 'std'],
    'Pressão': ['mean', 'min', 'max', 'std']
})
stats_df.columns = [''.join(col) for col in stats_df.columns]
stats_df.reset_index(inplace=True)

bimtra = bimtra.merge(stats_df, on="flightid", how="left")
# Preencher NaN na coluna de espera com 0 (sem espera)
bimtra

,flightid,origem,destino,dt_dep,dt_arr,target,linha,diaSemana,hora,HoraDataDest,...,Direção do Ventomax_y,Direção do Ventostd_y,Visibilidademean_y,Visibilidademin_y,Visibilidademax_y,Visibilidadestd_y,Pressãomean_y,Pressãomin_y,Pressãomax_y,Pressãostd_y
0,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ,2,0,2022-06-01 01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,c7c5c10716335b048f86d8c52fcba3f2,SBGR,SBRJ,2022-06-01 00:57:01,2022-06-01 01:32:53,2152,SBGRSBRJ,2,0,2022-06-01 01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3162de7203a972f071d5a48e8f0f4828,SBBR,SBRJ,2022-06-01 00:26:52,2022-06-01 01:43:45,4613,SBBRSBRJ,2,0,2022-06-01 01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8fcd243e9b9eebbe62ab145ce04b6ab5,SBKP,SBCF,2022-06-01 00:58:40,2022-06-01 01:41:41,2581,SBKPSBCF,2,0,2022-06-01 01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,504a62621cd231d6ab67e674ce538cd3,SBCF,SBFL,2022-06-01 01:00:38,2022-06-01 02:33:05,5547,SBCFSBFL,2,1,2022-06-01 02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286075,492598a440f1e952c3768b8ce7febc1f,SBBR,SBSP,2023-05-13 14:48:29,2023-05-13 16:08:05,4776,SBBRSBSP,5,14,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286076,766783c7267aead68c4c2452b0cd373f,SBPA,SBSP,2023-05-13 14:56:52,2023-05-13 16:12:14,4522,SBPASBSP,5,14,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286077,5c00d263d1cfc37deb53b5a7b7a2be75,SBCT,SBSP,2023-05-13 15:37:45,2023-05-13 16:18:34,2449,SBCTSBSP,5,15,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286078,64cedf597c56623e43c04bf4c16f9fa3,SBRJ,SBSP,2023-05-13 15:35:07,2023-05-13 16:23:51,2924,SBRJSBSP,5,15,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286079,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT,5,16,2023-05-13 17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
tcprev = pd.read_csv("data/tc-prev.csv")

In [62]:
tcprev["hora"] = pd.to_datetime(tcprev["hora"], unit='ms')

In [63]:
tcprev

                     hora  troca aero
0     2022-06-01 00:00:00      0   BR
1     2022-06-01 01:00:00      0   BR
2     2022-06-01 02:00:00      0   BR
3     2022-06-01 03:00:00      0   BR
4     2022-06-01 04:00:00      0   BR
...                   ...    ...  ...
93307 2023-04-15 19:00:00      1   SV
93308 2023-04-15 20:00:00      1   SV
93309 2023-04-15 21:00:00      1   SV
93310 2023-04-15 22:00:00      0   SV
93311 2023-04-15 23:00:00      0   SV

[93312 rows x 3 columns]

In [64]:
tcprev.to_csv("data/tc-prev-join.csv", index=False)

In [65]:
# Mesclar os dataframes usando a coluna "HoraData"
tcprev['HoraData'] = tcprev['hora'].dt.strftime('%Y-%m-%d %H')
df_merge = pd.merge(bimtra, tcprev, on='HoraData', how='left')

# Preencher NaN na coluna de espera com 0 (sem espera)
df_merge['troca'] = df_merge['troca'].fillna(0)
df_merge = df_merge.groupby("flightid").agg({"troca": "sum"})
bimtra = bimtra.merge(df_merge.reset_index(), on="flightid", how="left")

In [66]:
tcprev["diaSemana"] = tcprev["hora"].dt.dayofweek

tcprev["hora"] = tcprev["hora"].dt.hour
tcprev_hora = tcprev.groupby(["aero", "hora"]).agg({"troca": ["mean", "sum"]})
tcprev_sem = tcprev.groupby(["aero", "diaSemana"]).agg({"troca": ["mean", "sum"]})
tcprev_aero = tcprev.groupby(["aero"]).agg({"troca": ["mean", "sum"]})

In [67]:
tcreal = pd.read_csv("data/tc-real.csv")
tcreal["hora"] = pd.to_datetime(tcreal["hora"], unit='ms')
tcreal["diaSemana"] = tcreal["hora"].dt.dayofweek

tcreal['HoraData'] = tcreal['hora'].dt.strftime('%Y-%m-%d %H')
tcreal["hora"] = tcreal["hora"].dt.hour

In [68]:
#tcreal = pd.read_csv("data/tc-real.csv")
tcreal

       hora nova_cabeceira antiga_cabeceira aero  diaSemana       HoraData
0        14             32               03   FL          2  2022-06-01 14
1        18             18               12   RF          2  2022-06-01 18
2        19             16               13   CF          2  2022-06-01 19
3        19             15               26   GL          2  2022-06-01 19
4        19             15               26   GL          2  2022-06-01 19
...     ...            ...              ...  ...        ...            ...
31694    19             15               30   KP          5  2023-04-15 19
31695    20             17               10   SV          5  2023-04-15 20
31696    20             10               17   SV          5  2023-04-15 20
31697    20             15               08   GL          5  2023-04-15 20
31698    20             11               15   PA          5  2023-04-15 20

[31699 rows x 6 columns]

In [69]:
tcreal.to_csv("data/tc-real-join.csv", index=False)

In [70]:
# Mesclar os dataframes usando a coluna "HoraData"

df_merge = pd.merge(bimtra, tcreal, on='HoraData', how='left')

# Preencher NaN na coluna de espera com 0 (sem espera)
df_merge['trocareal'] = 1
df_merge = df_merge.groupby("flightid").agg({"trocareal": "sum"})
bimtra = bimtra.merge(df_merge.reset_index(), on="flightid", how="left")

In [71]:
bimtra

,flightid,origem,destino,dt_dep,dt_arr,target,linha,diaSemana,hora,HoraDataDest,...,Visibilidademean_y,Visibilidademin_y,Visibilidademax_y,Visibilidadestd_y,Pressãomean_y,Pressãomin_y,Pressãomax_y,Pressãostd_y,troca,trocareal
0,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ,2,0,2022-06-01 01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3
1,c7c5c10716335b048f86d8c52fcba3f2,SBGR,SBRJ,2022-06-01 00:57:01,2022-06-01 01:32:53,2152,SBGRSBRJ,2,0,2022-06-01 01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3
2,3162de7203a972f071d5a48e8f0f4828,SBBR,SBRJ,2022-06-01 00:26:52,2022-06-01 01:43:45,4613,SBBRSBRJ,2,0,2022-06-01 01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3
3,8fcd243e9b9eebbe62ab145ce04b6ab5,SBKP,SBCF,2022-06-01 00:58:40,2022-06-01 01:41:41,2581,SBKPSBCF,2,0,2022-06-01 01,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3
4,504a62621cd231d6ab67e674ce538cd3,SBCF,SBFL,2022-06-01 01:00:38,2022-06-01 02:33:05,5547,SBCFSBFL,2,1,2022-06-01 02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286075,492598a440f1e952c3768b8ce7febc1f,SBBR,SBSP,2023-05-13 14:48:29,2023-05-13 16:08:05,4776,SBBRSBSP,5,14,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
286076,766783c7267aead68c4c2452b0cd373f,SBPA,SBSP,2023-05-13 14:56:52,2023-05-13 16:12:14,4522,SBPASBSP,5,14,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
286077,5c00d263d1cfc37deb53b5a7b7a2be75,SBCT,SBSP,2023-05-13 15:37:45,2023-05-13 16:18:34,2449,SBCTSBSP,5,15,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
286078,64cedf597c56623e43c04bf4c16f9fa3,SBRJ,SBSP,2023-05-13 15:35:07,2023-05-13 16:23:51,2924,SBRJSBSP,5,15,2023-05-13 16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1
286079,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT,5,16,2023-05-13 17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1

In [72]:

tcreal_hora = tcreal.groupby(["aero", "hora"]).agg({"aero": ["count"]})
tcreal_sem = tcreal.groupby(["aero", "diaSemana"]).agg({"aero": ["count"]})
tcreal_aero = tcreal.groupby(["aero"]).agg({"aero": ["count"]})

In [73]:
tcreal_aero

       aero
      count
aero
BR     1153
CF      912
CT     1509
FL     6151
GL     2491
GR      814
KP     2060
PA      910
RF      780
RJ     2103
SP     1676
SV    11140

In [74]:
tcprev = pd.read_csv("data/tc-prev.csv")

In [75]:
bimtra["aero"] = bimtra["origem"].str[2:]

In [76]:
len(bimtra)

286080

In [77]:
tcprev_hora.reset_index(inplace=True)

In [78]:
tcprev_hora.columns = tcprev_hora.columns.droplevel(0)

In [79]:
tcprev_hora.columns = ["aero", "hora", "troca_prev_mean", "troca_prev_sum"]
tcprev_aero.reset_index(inplace=True)
tcprev_aero.columns = tcprev_aero.columns.droplevel(0)
tcprev_aero.columns = ["aero", "troca_prev_mean", "troca_prev_sum"]
tcprev_sem.reset_index(inplace=True)
tcprev_sem.columns = tcprev_sem.columns.droplevel(0)
tcprev_sem.columns = ["aero", "diaSemana", "troca_prev_mean", "troca_prev_sum"]
tcreal_hora.reset_index(inplace=True)
tcreal_hora.columns = tcreal_hora.columns.droplevel(0)
tcreal_hora.columns = ["aero", "hora", "troca_real"]
tcreal_aero.reset_index(inplace=True)
tcreal_aero.columns = tcreal_aero.columns.droplevel(0)
tcreal_aero.columns = ["aero", "troca_real"]
tcreal_sem.reset_index(inplace=True)
tcreal_sem.columns = tcreal_sem.columns.droplevel(0)
tcreal_sem.columns = ["aero", "diaSemana", "troca_real"]

In [80]:
bimtra.columns

Index(['flightid', 'origem', 'destino', 'dt_dep', 'dt_arr', 'target', 'linha',
       'diaSemana', 'hora', 'HoraDataDest', 'HoraData', 'esperas', 'aero_x',
       'mean_x', 'sum_x', 'aero_y', 'mean_y', 'sum_y', 'mean', 'sum',
       'Temperaturamean_x', 'Temperaturamin_x', 'Temperaturamax_x',
       'Temperaturastd_x', 'Ponto de Orvalhomean_x', 'Ponto de Orvalhomin_x',
       'Ponto de Orvalhomax_x', 'Ponto de Orvalhostd_x',
       'Velocidade do Ventomean_x', 'Velocidade do Ventomin_x',
       'Velocidade do Ventomax_x', 'Velocidade do Ventostd_x',
       'Direção do Ventomean_x', 'Direção do Ventomin_x',
       'Direção do Ventomax_x', 'Direção do Ventostd_x', 'Visibilidademean_x',
       'Visibilidademin_x', 'Visibilidademax_x', 'Visibilidadestd_x',
       'Pressãomean_x', 'Pressãomin_x', 'Pressãomax_x', 'Pressãostd_x',
       'Temperaturamean_y', 'Temperaturamin_y', 'Temperaturamax_y',
       'Temperaturastd_y', 'Ponto de Orvalhomean_y', 'Ponto de Orvalhomin_y',
       'Ponto de Orvalhomax_y', 'Ponto de Orvalhostd_y',
       'Velocidade do Ventomean_y', 'Velocidade do Ventomin_y',
       'Velocidade do Ventomax_y', 'Velocidade do Ventostd_y',
       'Direção do Ventomean_y', 'Direção do Ventomin_y',
       'Direção do Ventomax_y', 'Direção do Ventostd_y', 'Visibilidademean_y',
       'Visibilidademin_y', 'Visibilidademax_y', 'Visibilidadestd_y',
       'Pressãomean_y', 'Pressãomin_y', 'Pressãomax_y', 'Pressãostd_y',
       'troca', 'trocareal', 'aero'],
      dtype='object')

In [81]:
tcprev_hora.to_csv("data/tcprev_hora.csv", index=False)
tcprev_sem.to_csv("data/tcprev_sem.csv", index=False)
tcprev_aero.to_csv("data/tcprev_aero.csv", index=False)
tcreal_hora.to_csv("data/tcprev_hora.csv", index=False)
tcreal_sem.to_csv("data/tcprev_sem.csv", index=False)
tcreal_aero.to_csv("data/tcprev_aero.csv", index=False)

In [82]:
bimtra = bimtra.merge(tcprev_hora, on=["aero", "hora"], how="left")
bimtra = bimtra.merge(tcprev_sem, on=["aero", "diaSemana"], how="left")
bimtra = bimtra.merge(tcprev_aero, on=["aero"], how="left")
bimtra = bimtra.merge(tcreal_hora, on=["aero", "hora"], how="left")
bimtra = bimtra.merge(tcreal_sem, on=["aero", "diaSemana"], how="left")
bimtra = bimtra.merge(tcreal_aero, on=["aero"], how="left")
bimtra

,flightid,origem,destino,dt_dep,dt_arr,target,linha,diaSemana,hora,HoraDataDest,...,aero,troca_prev_mean_x,troca_prev_sum_x,troca_prev_mean_y,troca_prev_sum_y,troca_prev_mean,troca_prev_sum,troca_real_x,troca_real_y,troca_real
0,fcb2bf90345705318213ae1307c0f901,SBKP,SBRJ,2022-06-01 00:44:57,2022-06-01 01:26:00,2463,SBKPSBRJ,2,0,2022-06-01 01,...,KP,0.160494,52,0.293478,324,0.272119,2116,23.0,288,2060
1,c7c5c10716335b048f86d8c52fcba3f2,SBGR,SBRJ,2022-06-01 00:57:01,2022-06-01 01:32:53,2152,SBGRSBRJ,2,0,2022-06-01 01,...,GR,0.160494,52,0.293478,324,0.272119,2116,18.0,134,814
2,3162de7203a972f071d5a48e8f0f4828,SBBR,SBRJ,2022-06-01 00:26:52,2022-06-01 01:43:45,4613,SBBRSBRJ,2,0,2022-06-01 01,...,BR,0.160494,52,0.293478,324,0.272119,2116,35.0,210,1153
3,8fcd243e9b9eebbe62ab145ce04b6ab5,SBKP,SBCF,2022-06-01 00:58:40,2022-06-01 01:41:41,2581,SBKPSBCF,2,0,2022-06-01 01,...,KP,0.160494,52,0.293478,324,0.272119,2116,23.0,288,2060
4,504a62621cd231d6ab67e674ce538cd3,SBCF,SBFL,2022-06-01 01:00:38,2022-06-01 02:33:05,5547,SBCFSBFL,2,1,2022-06-01 02,...,CF,0.160494,52,0.293478,324,0.272119,2116,25.0,109,912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286075,492598a440f1e952c3768b8ce7febc1f,SBBR,SBSP,2023-05-13 14:48:29,2023-05-13 16:08:05,4776,SBBRSBSP,5,14,2023-05-13 16,...,BR,0.401235,130,0.303442,335,0.272119,2116,79.0,130,1153
286076,766783c7267aead68c4c2452b0cd373f,SBPA,SBSP,2023-05-13 14:56:52,2023-05-13 16:12:14,4522,SBPASBSP,5,14,2023-05-13 16,...,PA,0.401235,130,0.303442,335,0.272119,2116,73.0,109,910
286077,5c00d263d1cfc37deb53b5a7b7a2be75,SBCT,SBSP,2023-05-13 15:37:45,2023-05-13 16:18:34,2449,SBCTSBSP,5,15,2023-05-13 16,...,CT,0.395062,128,0.303442,335,0.272119,2116,103.0,192,1509
286078,64cedf597c56623e43c04bf4c16f9fa3,SBRJ,SBSP,2023-05-13 15:35:07,2023-05-13 16:23:51,2924,SBRJSBSP,5,15,2023-05-13 16,...,RJ,0.395062,128,0.303442,335,0.272119,2116,132.0,263,2103
286079,682470da44b73aa8972af79243c4e6e6,SBPA,SBCT,2023-05-13 16:25:47,2023-05-13 17:16:40,3053,SBPASBCT,5,16,2023-05-13 17,...,PA,0.395062,128,0.303442,335,0.272119,2116,61.0,109,910

In [83]:
train = bimtra.merge(resumo, right_on="linha_first", left_on="linha", how="left")

In [84]:
resumo

,linha_first,flightid_,dt_radar_<lambda>,dt_radar_<lambda>.1,dt_radar_<lambda>.2,dt_radar_<lambda>.3,flightlevel_mean,flightlevel_max,distancia_,flightlevel_std,flightlevel_std.1,speed_std,speed_std.1
0,NaN,count,mean,min,max,std,mean,mean,mean,std,mean,mean,std
1,SBBRSBCF,2864,3209.0209497206706,0.0,8277.0,505.1781074764571,223.1400324508525,352.60963687150837,575.834701784026,15.761247114997513,113.01220021738615,96.34732592058592,16.596938295458155
2,SBBRSBCT,1026,5533.775828460039,4.0,8166.0,566.9881268946964,281.1630883931095,368.1325536062378,1063.4677710301346,12.570011323594358,113.72575327754934,84.1176769694231,13.2054169916998
3,SBBRSBFL,336,6625.3125,4.0,14041.0,802.0591041375009,292.2188612817781,371.76785714285717,1284.1695049641773,14.999555259971018,115.93710014539403,78.8868858421317,13.861260443979065
4,SBBRSBGL,693,4503.103896103896,362.0,7138.0,523.8152618016763,259.70783363369543,368.13852813852816,887.5042925637619,13.09356154145346,122.23862626914057,92.58519039880454,15.665866076042905
...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,SBSVSBKP,1494,7367.996653279786,121.0,12302.0,761.483020478947,305.5601352677385,369.2289156626506,1426.4242748944434,17.322919144273627,102.05840475491932,68.243716105359,16.668224626368342
133,SBSVSBPA,79,11771.683544303798,1683.0,13623.0,1455.2232848701617,324.43509942690906,375.1898734177215,2277.3825023041554,8.22824879734405,99.87921093160097,62.36285594137942,8.362795726130804
134,SBSVSBRF,1628,3782.2782555282556,0.0,9182.0,518.3340796845335,226.5958387344471,362.3673218673219,643.4232339847347,15.844889254045219,127.2252417382822,97.0024814261082,14.503895888882802
135,SBSVSBRJ,1810,6713.546408839779,843.0,10924.0,610.7180291362184,291.8831591581199,378.5779005524862,1226.6727911976184,12.48055842996475,124.12399364375192,82.78344889091554,13.068023636248327
136,SBSVSBSP,3866,7808.403776513192,305.0,22083.0,970.6857858639729,303.3405694075722,369.55380237972065,1453.1620287057992,17.806879818186644,103.47390427123766,69.3571629501052,17.56639419188513

In [85]:
#esperas_semana.to_csv("data/esperas_semana.csv", index=False)
#esperas_hora.to_csv("data/esperas_hora.csv", index=False)

In [86]:
esperas

       esperas  hora  aero              dt_dep  diaSemana       HoraData
0            0     0  SBBR 2022-06-01 00:00:00          2  2022-06-01 00
1            0     1  SBBR 2022-06-01 01:00:00          2  2022-06-01 01
2            0     2  SBBR 2022-06-01 02:00:00          2  2022-06-01 02
3            0     3  SBBR 2022-06-01 03:00:00          2  2022-06-01 03
4            0     4  SBBR 2022-06-01 04:00:00          2  2022-06-01 04
...        ...   ...   ...                 ...        ...            ...
93307        0    19  SBSV 2023-04-15 19:00:00          5  2023-04-15 19
93308        0    20  SBSV 2023-04-15 20:00:00          5  2023-04-15 20
93309        0    21  SBSV 2023-04-15 21:00:00          5  2023-04-15 21
93310        0    22  SBSV 2023-04-15 22:00:00          5  2023-04-15 22
93311        0    23  SBSV 2023-04-15 23:00:00          5  2023-04-15 23

[93312 rows x 6 columns]

In [87]:
train["origem"], origem = pd.factorize(train["origem"]) #verificar se rodando novamente muda de código
train["destino"], destino = pd.factorize(train["destino"])

In [88]:
train["linha"], linha = pd.factorize(train["linha"])

In [89]:
pd.Series(origem).to_csv("data/origem.csv", index=False)
pd.Series(destino).to_csv("data/destino.csv", index=False)
pd.Series(linha).to_csv("data/linha.csv", index=False)

In [90]:
del train["linha_first"]

In [91]:
del train["dt_dep"], train["dt_arr"], train["aero_x"]

In [92]:
del train["aero_y"]

In [93]:
del train["aero"]

In [95]:
for col in train.columns:
    print(col)

flightid
origem
destino
target
linha
diaSemana
hora
HoraDataDest
HoraData
esperas
mean_x
sum_x
mean_y
sum_y
mean
sum
Temperaturamean_x
Temperaturamin_x
Temperaturamax_x
Temperaturastd_x
Ponto de Orvalhomean_x
Ponto de Orvalhomin_x
Ponto de Orvalhomax_x
Ponto de Orvalhostd_x
Velocidade do Ventomean_x
Velocidade do Ventomin_x
Velocidade do Ventomax_x
Velocidade do Ventostd_x
Direção do Ventomean_x
Direção do Ventomin_x
Direção do Ventomax_x
Direção do Ventostd_x
Visibilidademean_x
Visibilidademin_x
Visibilidademax_x
Visibilidadestd_x
Pressãomean_x
Pressãomin_x
Pressãomax_x
Pressãostd_x
Temperaturamean_y
Temperaturamin_y
Temperaturamax_y
Temperaturastd_y
Ponto de Orvalhomean_y
Ponto de Orvalhomin_y
Ponto de Orvalhomax_y
Ponto de Orvalhostd_y
Velocidade do Ventomean_y
Velocidade do Ventomin_y
Velocidade do Ventomax_y
Velocidade do Ventostd_y
Direção do Ventomean_y
Direção do Ventomin_y
Direção do Ventomax_y
Direção do Ventostd_y
Visibilidademean_y
Visibilidademin_y
Visibilidademax_y
Visibilidadestd_y
Pressãomean_y
Pressãomin_y
Pressãomax_y
Pressãostd_y
troca
trocareal
troca_prev_mean_x
troca_prev_sum_x
troca_prev_mean_y
troca_prev_sum_y
troca_prev_mean
troca_prev_sum
troca_real_x
troca_real_y
troca_real
flightid_
dt_radar_<lambda>
dt_radar_<lambda>.1
dt_radar_<lambda>.2
dt_radar_<lambda>.3
flightlevel_mean
flightlevel_max
distancia_
flightlevel_std
flightlevel_std.1
speed_std
speed_std.1

In [95]:
flightThrought = pd.read_csv("data/flightThourghtArea2.csv")

In [96]:
len(train)

286080

In [97]:
train = train.merge(flightThrought, on="flightid", how="left")

In [98]:

train.columns = [re.sub('[\[\]<>\'"\'.,]', '', col) for col in train.columns]
train.to_csv("data/train_with_flight_v2_greather_1500.csv", index=False)