In [2]:
import pandas as pd
cat62 = pd.read_csv('data/cat62.csv')

In [3]:
bimtra = pd.read_csv('data/bimtra.csv')

In [4]:
bimtra["linha"] = bimtra["origem"] + bimtra["destino"]

In [5]:
bimtra = bimtra.groupby("flightid")["linha"].first()

In [6]:
bimtra = pd.DataFrame(bimtra).reset_index()

In [7]:
bimtra

                                flightid     linha
0       0000f76a51b99be3f181ea2b201b34ef  SBSVSBGR
1       00010bb2c49076d56a9815122fefc8aa  SBCFSBSP
2       00010ed6d09c78b5a37f4df13f524f56  SBSVSBSP
3       000143522a56fa245543e477c74fd908  SBSPSBRF
4       00014fa436546dfdc7a67919e9e1ea47  SBCFSBFL
...                                  ...       ...
262411  fffea9a5cfeeb8f24e738cf60a1d5f2b  SBGRSBPA
262412  fffeba6342187a9ee0caff2526e4ff0e  SBSPSBPA
262413  ffff413d10cfbb298a9411855e80a0f0  SBRJSBPA
262414  ffffd0e5ce497de7ddf3d34d19b9ce3a  SBSPSBRJ
262415  ffffd4331f8b78c6e726eda4e6a2f5ac  SBGRSBRF

[262416 rows x 2 columns]

In [8]:
cat62 = cat62.merge(bimtra, on="flightid", how="left")

In [9]:
cat62

,flightid,lat,lon,flightlevel,speed,dt_radar,linha
0,62e589aaa96762725b092b898d48a35e,-25.044874,-48.453541,210.0,266.0,1.654056e+12,SBPASBGR
1,62e589aaa96762725b092b898d48a35e,-23.513367,-47.060570,105.0,266.0,1.654057e+12,SBPASBGR
2,62e589aaa96762725b092b898d48a35e,-23.515486,-47.065519,106.0,266.0,1.654057e+12,SBPASBGR
3,62e589aaa96762725b092b898d48a35e,-29.233669,-50.641993,177.0,221.0,1.654052e+12,SBPASBGR
4,62e589aaa96762725b092b898d48a35e,-28.122698,-50.041957,210.0,270.0,1.654053e+12,SBPASBGR
...,...,...,...,...,...,...,...
37122487,0330f20d67f552088ed730f06f0c8e1b,-29.440907,-50.955963,245.0,434.0,1.684007e+12,NaN
37122488,0330f20d67f552088ed730f06f0c8e1b,-29.524358,-51.206169,197.0,406.0,1.684007e+12,NaN
37122489,0330f20d67f552088ed730f06f0c8e1b,-23.524014,-46.725162,46.0,162.0,1.684011e+12,NaN
37122490,0330f20d67f552088ed730f06f0c8e1b,-26.768997,-48.395374,350.0,446.0,1.684009e+12,NaN
37122491,0330f20d67f552088ed730f06f0c8e1b,-28.066242,-49.496078,350.0,457.0,1.684008e+12,NaN

In [10]:
#import numpy as np
## Convert dt_radar to datetime
#cat62['dt_radar'] = pd.to_datetime(cat62['dt_radar'], unit='ms')
#
## Calculate flight time for each flightid
#cat62['flight_time'] = cat62.groupby('flightid')['dt_radar'].transform(lambda x: x.max() - x.min())
#
## Convert flight time to seconds for easier calculation
#cat62['flight_time'] = cat62['flight_time'].dt.total_seconds()
#
## Get mean and std for each linha
#grouped = cat62.groupby('linha')['flight_time'].agg(['mean', 'std'])
#
## Merge the stats back into the original dataframe
#df = cat62.merge(grouped, left_on = 'linha', right_index = True)
#
## Calculate the z-score for each flightid in each linha
#df['z_score'] = np.abs((df['flight_time'] - df['mean']) / df['std'])

In [11]:
#df.dropna(inplace=True)
#df

In [12]:

# Find the flightid with the minimum z-score (closest to the mean) for each linha
#result = df.loc[df.groupby('linha')['z_score'].idxmin()][['linha', 'flightid']]

In [13]:
#result.to_csv("data/normal_routes.csv", index=False)

In [14]:
import pandas as pd
normal_routes = pd.read_csv("data/normal_routes.csv")

In [15]:
# Ensure that 'flightid' is the index in the 'normal_routes' Dataframe 
normal_routes.set_index('flightid', inplace=True)

# Filter the 'cat62' DataFrame
filtered_cat62 = cat62[cat62['flightid'].isin(normal_routes.index)]

In [16]:
filtered_cat62 = filtered_cat62.sort_values(['flightid', 'dt_radar'])

# Indexando o dataframe
filtered_cat62 = filtered_cat62.reset_index(drop=True)

# Agrupando por 'flightid' e selecionando uma linha a cada 3
filtered_cat62 = filtered_cat62.groupby('flightid').nth(list(range(0, len(filtered_cat62), 7)))

In [17]:
filtered_cat62

,flightid,lat,lon,flightlevel,speed,dt_radar,linha
0,01a799a44a29a7c636601fe9fb6e9e54,-25.515188,-49.190120,NaN,203.0,1.658995e+12,SBCTSBGR
7,01a799a44a29a7c636601fe9fb6e9e54,-25.009826,-48.853066,176.0,400.0,1.658996e+12,SBCTSBGR
14,01a799a44a29a7c636601fe9fb6e9e54,-24.637614,-48.541516,252.0,429.0,1.658996e+12,SBCTSBGR
21,01a799a44a29a7c636601fe9fb6e9e54,-24.339243,-48.293025,270.0,442.0,1.658996e+12,SBCTSBGR
28,01a799a44a29a7c636601fe9fb6e9e54,-23.962922,-47.984450,246.0,426.0,1.658997e+12,SBCTSBGR
...,...,...,...,...,...,...,...
20275,ff70a92a4d8da0e0c4798eb52d05646f,-28.991872,-50.583433,279.0,389.0,1.675822e+12,SBKPSBPA
20282,ff70a92a4d8da0e0c4798eb52d05646f,-29.277269,-50.897612,201.0,344.0,1.675822e+12,SBKPSBPA
20289,ff70a92a4d8da0e0c4798eb52d05646f,-29.668378,-51.257837,96.0,294.0,1.675822e+12,SBKPSBPA
20296,ff70a92a4d8da0e0c4798eb52d05646f,-29.991293,-51.358985,27.0,224.0,1.675823e+12,SBKPSBPA
20303,ff70a92a4d8da0e0c4798eb52d05646f,-29.991310,-51.215838,6.0,119.0,1.675823e+12,SBKPSBPA

In [18]:
import pandas as pd
test = pd.read_csv('data/idsc_dataset.csv', delimiter=';')
test = test[["flightid", "origem", "destino", "hora_ref", "path", "dt_dep"]]

In [19]:
#test.to_csv("data/idsc_dataset_v2.csv", index=False)

In [17]:
test

,flightid,origem,destino,hora_ref,dt_dep,snapshot_radar,path,hora_esperas,esperas,aero_esperas,...,metaf,aero_metaf,hora_metar,metar,aero_metar,hora_tcp,troca,aero_tcp,hora_tcr,aero_tcr
0,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,11:53:30,MULTIPOINT ((-0.9862962481402141 -0.2329259019...,http://satelite.cptec.inpe.br/repositoriogoes/...,10:00:00,1,SBSP,...,METAF SBSP 211100Z 32007KT 9999 SCT033 ...,SBSP,10:00:00,METAR SBSP 211000Z 34007KT 290V010 CAVOK 18/13...,SBSP,11:00:00,0.0,SBSP,NaN,NaN
1,865dbbbe74bebea18a71f24342516ff0,SBSP,SBCT,00:00:00,00:04:37,MULTIPOINT ((-0.8863534722346053 -0.5093356150...,http://satelite.cptec.inpe.br/repositoriogoes/...,23:00:00,0,SBCT,...,METAF SBCT 150000Z 11008KT 1000 BR OVC033...,SBCT,23:00:00,METAR SBCT 142300Z 13005KT 100V200 CAVOK 11/06...,SBCT,00:00:00,0.0,SBCT,23:00:00,SBCT
2,1803af9cfc6a2c74d188481e3ffd848e,SBGR,SBPA,01:00:00,01:33:15,MULTIPOINT ((-0.8966138193125871 -0.5115119601...,http://satelite.cptec.inpe.br/repositoriogoes/...,00:00:00,0,SBPA,...,METAF SBPA 030100Z 08005KT 9999 SCT011 ...,SBPA,00:00:00,METAR SBPA 030000Z 07004KT 030V090 9000 NSC 21...,SBPA,01:00:00,0.0,SBPA,NaN,NaN
3,f6af733a687f904183efd149ec713be5,SBCT,SBSV,03:00:00,03:54:14,MULTIPOINT ((-0.8586718860112791 -0.4418648049...,http://satelite.cptec.inpe.br/repositoriogoes/...,02:00:00,0,SBSV,...,NaN,NaN,02:00:00,METAR SBSV 150200Z 06009KT 9999 SCT020 25/22 Q...,SBSV,03:00:00,0.0,SBSV,02:00:00,SBSV
4,6117f9ac60b7f66b740c9130be433313,SBRJ,SBGR,00:00:00,00:27:32,MULTIPOINT ((-0.8914635585346382 -0.5234904405...,http://satelite.cptec.inpe.br/repositoriogoes/...,23:00:00,0,SBGR,...,METAF SBGR 230000Z 32008KT CAVOK 24/04 Q1010=\n,SBGR,23:00:00,METAR COR SBGR 222300Z 06004KT CAVOK 23/08 Q1013=,SBGR,00:00:00,0.0,SBGR,23:00:00,SBGR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40034,4e08052066073297c7a3c55798618324,SBSV,SBRF,20:00:00,20:25:00,MULTIPOINT ((-0.8955415064673201 -0.5234137952...,http://satelite.cptec.inpe.br/repositoriogoes/...,19:00:00,0,SBRF,...,NaN,NaN,19:00:00,METAR SBRF 181900Z 19015KT 9999 SCT023 BKN060 ...,SBRF,20:00:00,0.0,SBRF,NaN,NaN
40035,e22f120c65f5759aa8df576b59d71be3,SBCT,SBSP,08:00:00,08:50:22,MULTIPOINT ((-0.8903194203987348 -0.5144905777...,http://satelite.cptec.inpe.br/repositoriogoes/...,07:00:00,0,SBSP,...,METAF SBSP 090800Z 36003KT CAVOK 19/10 Q1017=\n,SBSP,07:00:00,METAR SBSP 090700Z AUTO VRB02KT CAVOK 19/17 Q1...,SBSP,08:00:00,0.0,SBSP,NaN,NaN
40036,ca9399162037201a4d0c49c832a32739,SBGR,SBCF,11:00:00,11:30:03,MULTIPOINT ((-0.8963144777278773 -0.5234059876...,http://satelite.cptec.inpe.br/repositoriogoes/...,10:00:00,0,SBCF,...,METAF SBCF 221100Z 13004KT CAVOK 21/09 Q1016=\n,SBCF,10:00:00,METAR SBCF 221000Z 16003KT 9000 NSC 13/12 Q1018=,SBCF,11:00:00,0.0,SBCF,NaN,NaN
40037,560136088f5f1493dbad809a3554172c,SBBR,SBGR,12:00:00,12:25:21,NaN,http://satelite.cptec.inpe.br/repositoriogoes/...,11:00:00,0,SBGR,...,METAF SBGR 231200Z 34010KT CAVOK 25/07 Q1012=\n,SBGR,11:00:00,METAR SBGR 231100Z 03004KT CAVOK 25/10 Q1014=,SBGR,12:00:00,0.0,SBGR,NaN,NaN
40038,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,00:59:07,MULTIPOINT ((-0.8995693853177327 -0.4320829335...,http://satelite.cptec.inpe.br/repositoriogoes/...,23:00:00,0,SBPA,...,METAF SBPA 050000Z 20006KT 2000 BR OVC033...,SBPA,23:00:00,METAR SBPA 042300Z VRB02KT 8000 OVC009 17/16 Q...,SBPA,00:00:00,0.0,SBPA,NaN,NaN

In [20]:
test["linha"] = test["origem"] + test["destino"]

In [21]:
test.shape

(40039, 7)

In [22]:
del filtered_cat62["flightid"]

In [23]:
filtered_cat62

             lat        lon  flightlevel  speed      dt_radar     linha
0     -25.515188 -49.190120          NaN  203.0  1.658995e+12  SBCTSBGR
7     -25.009826 -48.853066        176.0  400.0  1.658996e+12  SBCTSBGR
14    -24.637614 -48.541516        252.0  429.0  1.658996e+12  SBCTSBGR
21    -24.339243 -48.293025        270.0  442.0  1.658996e+12  SBCTSBGR
28    -23.962922 -47.984450        246.0  426.0  1.658997e+12  SBCTSBGR
...          ...        ...          ...    ...           ...       ...
20275 -28.991872 -50.583433        279.0  389.0  1.675822e+12  SBKPSBPA
20282 -29.277269 -50.897612        201.0  344.0  1.675822e+12  SBKPSBPA
20289 -29.668378 -51.257837         96.0  294.0  1.675822e+12  SBKPSBPA
20296 -29.991293 -51.358985         27.0  224.0  1.675823e+12  SBKPSBPA
20303 -29.991310 -51.215838          6.0  119.0  1.675823e+12  SBKPSBPA

[2958 rows x 6 columns]

In [24]:
test = test.merge(filtered_cat62, on="linha", how="left")

In [25]:
test

,flightid,origem,destino,hora_ref,path,dt_dep,linha,lat,lon,flightlevel,speed,dt_radar
0,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-15.877232,-47.902185,37.0,168.0,1.662463e+12
1,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.076419,-47.826310,121.0,288.0,1.662463e+12
2,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.461348,-47.715259,224.0,385.0,1.662464e+12
3,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.816225,-47.611974,280.0,444.0,1.662464e+12
4,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-17.459661,-47.423791,359.0,493.0,1.662464e+12
...,...,...,...,...,...,...,...,...,...,...,...,...
740944,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.525482,-50.715443,137.0,301.0,1.655320e+12
740945,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.921180,-50.730029,65.0,242.0,1.655320e+12
740946,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-30.149833,-50.767835,49.0,223.0,1.655321e+12
740947,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-30.099181,-50.903831,40.0,189.0,1.655321e+12
740948,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.994128,-51.063442,14.0,168.0,1.655321e+12

In [26]:
test.to_csv("data/test_cat62.csv", index=False) #finaliza aq

In [90]:
for col in test.columns:
    print(col)

flightid
origem
destino
hora_ref
dt_dep
snapshot_radar
path
hora_esperas
esperas
aero_esperas
hora_metaf
metaf
aero_metaf
hora_metar
metar
aero_metar
hora_tcp
troca
aero_tcp
hora_tcr
aero_tcr
linha
lat
lon
flightlevel
speed
dt_radar
flight_time

In [27]:
import pandas as pd
test = pd.read_csv('data/test_cat62.csv')

In [28]:
test["dt_radar"] = pd.to_datetime(test["dt_radar"], unit='ms')
test

,flightid,origem,destino,hora_ref,path,dt_dep,linha,lat,lon,flightlevel,speed,dt_radar
0,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-15.877232,-47.902185,37.0,168.0,2022-09-06 11:19:00
1,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.076419,-47.826310,121.0,288.0,2022-09-06 11:22:04
2,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.461348,-47.715259,224.0,385.0,2022-09-06 11:26:01
3,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.816225,-47.611974,280.0,444.0,2022-09-06 11:29:06
4,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-17.459661,-47.423791,359.0,493.0,2022-09-06 11:34:03
...,...,...,...,...,...,...,...,...,...,...,...,...
740944,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.525482,-50.715443,137.0,301.0,2022-06-15 19:07:06
740945,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.921180,-50.730029,65.0,242.0,2022-06-15 19:13:03
740946,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-30.149833,-50.767835,49.0,223.0,2022-06-15 19:17:00
740947,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-30.099181,-50.903831,40.0,189.0,2022-06-15 19:20:05
740948,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.994128,-51.063442,14.0,168.0,2022-06-15 19:24:01

In [29]:
aux = test.groupby("flightid")["data"].first()

KeyError: 'Column not found: data'

In [ ]:
aux = pd.DataFrame(aux).reset_index()
aux

                               flightid                data
0      00054c16230f8fb7cf565233af432bb8 2023-09-02 19:00:00
1      0005c08c2b064c695fac495d7a6b86b5 2023-08-17 08:00:00
2      00062261eae0cd9c9d44aba8d0e41617 2023-09-07 11:00:00
3      000625db56237c20414beebf94aab0d3 2023-08-15 22:00:00
4      0007f2ee7329b979f8d4187c5ea9670b 2023-09-13 00:00:00
...                                 ...                 ...
40034  fffac2757793e7abe724a23a4edb3371 2023-08-15 22:00:00
40035  fffc60c41625dd5fa17fc34d09b9b1d9 2023-09-10 13:00:00
40036  ffff94d470e6aa3bf4ae1f3649fdf1f0 2023-09-15 22:00:00
40037  ffff96ee92bf9da75c93a22669ff4811 2023-09-11 14:00:00
40038  ffffa7751e3a4ac054c0485b600bf630                 NaT

[40039 rows x 2 columns]

In [ ]:
aux["fdata"] = aux["data"]
del aux["data"]

In [ ]:
test = test.merge(aux, on="flightid", how="left")

In [ ]:
test["diff_date"] = test["fdata"] - test["dt_radar"]

In [ ]:
test["dt_radar"] = test["dt_radar"] + test["diff_date"]

In [ ]:
test

,flightid,origem,destino,hora_ref,path,dt_dep,linha,lat,lon,flightlevel,speed,dt_radar,data,diff_date,fdata
0,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-21.566934,-46.786967,390.0,493.0,2023-08-21 11:00:00,2023-08-21 11:00:00,348 days 22:54:57,2023-08-21 11:00:00
1,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-20.214075,-46.985819,390.0,487.0,2023-08-21 11:00:00,2023-08-21 11:00:00,348 days 23:05:00,2023-08-21 11:00:00
2,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-23.491932,-47.056154,83.0,237.0,2023-08-21 11:00:00,2023-08-21 11:00:00,348 days 22:32:00,2023-08-21 11:00:00
3,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-23.361904,-47.081812,97.0,240.0,2023-08-21 11:00:00,2023-08-21 11:00:00,348 days 22:34:00,2023-08-21 11:00:00
4,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-18.248203,-47.295240,390.0,482.0,2023-08-21 11:00:00,2023-08-21 11:00:00,348 days 23:19:56,2023-08-21 11:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5052222,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.144617,-50.702264,191.0,360.0,2023-09-05 00:00:00,2023-09-05 00:00:00,446 days 04:56:58,2023-09-05 00:00:00
5052223,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.995381,-51.014212,22.0,175.0,2023-09-05 00:00:00,2023-09-05 00:00:00,446 days 04:36:55,2023-09-05 00:00:00
5052224,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-28.053176,-49.871894,360.0,441.0,2023-09-05 00:00:00,2023-09-05 00:00:00,446 days 05:08:54,2023-09-05 00:00:00
5052225,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-30.153200,-50.878138,47.0,186.0,2023-09-05 00:00:00,2023-09-05 00:00:00,446 days 04:40:59,2023-09-05 00:00:00
5052226,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.149470,-50.700959,190.0,345.0,2023-09-05 00:00:00,2023-09-05 00:00:00,446 days 04:56:54,2023-09-05 00:00:00

In [30]:
test["data"] = pd.to_datetime(test["data"])

KeyError: 'data'

In [5]:
test["diff_date"] = test["data"] - test["dt_radar"]

In [31]:
test

,flightid,origem,destino,hora_ref,path,dt_dep,linha,lat,lon,flightlevel,speed,dt_radar
0,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-15.877232,-47.902185,37.0,168.0,2022-09-06 11:19:00
1,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.076419,-47.826310,121.0,288.0,2022-09-06 11:22:04
2,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.461348,-47.715259,224.0,385.0,2022-09-06 11:26:01
3,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.816225,-47.611974,280.0,444.0,2022-09-06 11:29:06
4,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-17.459661,-47.423791,359.0,493.0,2022-09-06 11:34:03
...,...,...,...,...,...,...,...,...,...,...,...,...
740944,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.525482,-50.715443,137.0,301.0,2022-06-15 19:07:06
740945,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.921180,-50.730029,65.0,242.0,2022-06-15 19:13:03
740946,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-30.149833,-50.767835,49.0,223.0,2022-06-15 19:17:00
740947,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-30.099181,-50.903831,40.0,189.0,2022-06-15 19:20:05
740948,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.994128,-51.063442,14.0,168.0,2022-06-15 19:24:01

In [5]:
storm = pd.read_csv('data/test_storm_areas')

In [10]:
storm["data"] = pd.to_datetime(storm["data"])

In [11]:
storm[storm["data"] > pd.to_datetime("20230821")]

,polygon,centroid_x,centroid_y,area_estimate,poly,data,lat,lon
52284,"('S11635384_202308210100.jpg.jpg', 0)",1444.999463,1072.980167,344353.5,0,2023-08-21 01:00:00,-55.684564,-5.724837
52285,"('S11635384_202308210100.jpg.jpg', 1)",1221.104660,1844.708510,242367.5,1,2023-08-21 01:00:00,-64.930351,-37.534075
52286,"('S11635384_202308210100.jpg.jpg', 2)",1687.701603,2081.989203,125162.0,2,2023-08-21 01:00:00,-45.662123,-47.314353
52287,"('S11635384_202308210100.jpg.jpg', 3)",1856.314547,1549.202689,89408.0,3,2023-08-21 01:00:00,-38.699213,-25.353862
52288,"('S11635384_202308210100.jpg.jpg', 4)",1467.161257,808.233680,29208.0,4,2023-08-21 01:00:00,-54.769388,5.187532
...,...,...,...,...,...,...,...,...
409030,"('S11635384_202309250000.jpg.jpg', 464)",941.500000,974.000000,12.0,464,2023-09-25 00:00:00,-76.476690,-1.645054
409031,"('S11635384_202309250000.jpg.jpg', 465)",1761.500000,741.000000,10.0,465,2023-09-25 00:00:00,-42.614602,7.958782
409032,"('S11635384_202309250000.jpg.jpg', 466)",1889.000000,2190.000000,8.0,466,2023-09-25 00:00:00,-37.349460,-51.766362
409033,"('S11635384_202309250000.jpg.jpg', 467)",1325.000000,2190.000000,8.0,467,2023-09-25 00:00:00,-60.639969,-51.766362
409034,"('S11635384_202309250000.jpg.jpg', 468)",941.000000,754.000000,8.0,468,2023-09-25 00:00:00,-76.497338,7.422945

In [32]:
test["data"] = pd.to_datetime(test["path"].str.split("/").str[-1].str.split("_", expand=True)[1].str.split(".", expand=True)[0])

In [33]:
test

,flightid,origem,destino,hora_ref,path,dt_dep,linha,lat,lon,flightlevel,speed,dt_radar,data
0,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-15.877232,-47.902185,37.0,168.0,2022-09-06 11:19:00,2023-08-21 11:00:00
1,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.076419,-47.826310,121.0,288.0,2022-09-06 11:22:04,2023-08-21 11:00:00
2,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.461348,-47.715259,224.0,385.0,2022-09-06 11:26:01,2023-08-21 11:00:00
3,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-16.816225,-47.611974,280.0,444.0,2022-09-06 11:29:06,2023-08-21 11:00:00
4,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,11:53:30,SBBRSBSP,-17.459661,-47.423791,359.0,493.0,2022-09-06 11:34:03,2023-08-21 11:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
740944,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.525482,-50.715443,137.0,301.0,2022-06-15 19:07:06,2023-09-05 00:00:00
740945,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.921180,-50.730029,65.0,242.0,2022-06-15 19:13:03,2023-09-05 00:00:00
740946,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-30.149833,-50.767835,49.0,223.0,2022-06-15 19:17:00,2023-09-05 00:00:00
740947,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-30.099181,-50.903831,40.0,189.0,2022-06-15 19:20:05,2023-09-05 00:00:00
740948,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,http://satelite.cptec.inpe.br/repositoriogoes/...,00:59:07,SBGRSBPA,-29.994128,-51.063442,14.0,168.0,2022-06-15 19:24:01,2023-09-05 00:00:00

In [9]:
test.to_csv("data/test_cat62.csv", index=False)

In [31]:
test["dt_radar"] = pd.to_datetime(test["dt_radar"], unit="ms")

In [32]:
test["dt_dep"] = pd.to_datetime(test["dt_dep"])

/tmp/ipykernel_416269/2456941913.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  test["dt_dep"] = pd.to_datetime(test["dt_dep"])

In [34]:
test = test.sort_values(by=['flightid', 'dt_radar'])

# Obter a primeira ocorrência de route_event por flightid e calcular a diferença com flight_start
first_route_event = test.groupby('flightid')[['flightid','dt_radar']].transform('first')

In [ ]:
test = test.merge(first_route_event, on="flightid", how="left")

In [ ]:
aux = test.groupby('flightid')['dt_radar'].transform('first')

,flightid,origem,destino,dt_dep,hora_ref,snapshot_radar,path,hora_esperas,esperas,aero_esperas,...,hora_tcr,aero_tcr,linha,lat,lon,flightlevel,speed,dt_radar,time_difference,route_event
0,7945735584a3297121c4f5ae0de8ecd1,SBKP,SBSV,2023-05-30 11:36:03,2023-05-30 11:00:00.000,MULTIPOINT ((-0.8807200448127578 -0.5148453155...,http://satelite.cptec.inpe.br/repositoriogoes/...,2023-05-30 10:00:00.000,0,SBSV,...,NaN,NaN,SBKPSBSV,-17.683022,-42.254237,350.0,497.0,2022-06-01 18:03:06,7,2023-05-30 11:43:03
1,7945735584a3297121c4f5ae0de8ecd1,SBKP,SBSV,2023-05-30 11:36:03,2023-05-30 11:00:00.000,MULTIPOINT ((-0.8807200448127578 -0.5148453155...,http://satelite.cptec.inpe.br/repositoriogoes/...,2023-05-30 10:00:00.000,0,SBSV,...,NaN,NaN,SBKPSBSV,-17.596812,-42.184386,350.0,497.0,2022-06-01 18:04:02,7,2023-05-30 11:43:03
2,7945735584a3297121c4f5ae0de8ecd1,SBKP,SBSV,2023-05-30 11:36:03,2023-05-30 11:00:00.000,MULTIPOINT ((-0.8807200448127578 -0.5148453155...,http://satelite.cptec.inpe.br/repositoriogoes/...,2023-05-30 10:00:00.000,0,SBSV,...,NaN,NaN,SBKPSBSV,-17.575394,-42.166778,350.0,497.0,2022-06-01 18:04:06,7,2023-05-30 11:43:03
3,7945735584a3297121c4f5ae0de8ecd1,SBKP,SBSV,2023-05-30 11:36:03,2023-05-30 11:00:00.000,MULTIPOINT ((-0.8807200448127578 -0.5148453155...,http://satelite.cptec.inpe.br/repositoriogoes/...,2023-05-30 10:00:00.000,0,SBSV,...,NaN,NaN,SBKPSBSV,-17.475093,-42.085838,350.0,496.0,2022-06-01 18:05:02,7,2023-05-30 11:43:03
4,7945735584a3297121c4f5ae0de8ecd1,SBKP,SBSV,2023-05-30 11:36:03,2023-05-30 11:00:00.000,MULTIPOINT ((-0.8807200448127578 -0.5148453155...,http://satelite.cptec.inpe.br/repositoriogoes/...,2023-05-30 10:00:00.000,0,SBSV,...,NaN,NaN,SBKPSBSV,-21.378438,-45.169273,350.0,512.0,2022-06-01 17:30:05,6,2023-05-30 11:42:03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12668,c3c8b46a8d4c0a09565b1c61a475d2d9,SBSP,SBCT,2023-05-20 13:35:06,2023-05-20 13:00:00.000,MULTIPOINT ((-0.8911832312799806 -0.5097777857...,http://satelite.cptec.inpe.br/repositoriogoes/...,2023-05-20 12:00:00.000,0,SBCT,...,2023-05-20 13:00:00.000,SBCT,SBSPSBCT,-23.871106,-47.092488,171.0,336.0,2022-06-10 10:37:05,-3,2023-05-20 13:32:06
12669,c3c8b46a8d4c0a09565b1c61a475d2d9,SBSP,SBCT,2023-05-20 13:35:06,2023-05-20 13:00:00.000,MULTIPOINT ((-0.8911832312799806 -0.5097777857...,http://satelite.cptec.inpe.br/repositoriogoes/...,2023-05-20 12:00:00.000,0,SBCT,...,2023-05-20 13:00:00.000,SBCT,SBSPSBCT,-25.565582,-48.929200,79.0,232.0,2022-06-10 11:03:01,-2,2023-05-20 13:33:06
12670,c3c8b46a8d4c0a09565b1c61a475d2d9,SBSP,SBCT,2023-05-20 13:35:06,2023-05-20 13:00:00.000,MULTIPOINT ((-0.8911832312799806 -0.5097777857...,http://satelite.cptec.inpe.br/repositoriogoes/...,2023-05-20 12:00:00.000,0,SBCT,...,2023-05-20 13:00:00.000,SBCT,SBSPSBCT,-25.603973,-49.090110,48.0,144.0,2022-06-10 11:07:06,-2,2023-05-20 13:33:06
12671,c3c8b46a8d4c0a09565b1c61a475d2d9,SBSP,SBCT,2023-05-20 13:35:06,2023-05-20 13:00:00.000,MULTIPOINT ((-0.8911832312799806 -0.5097777857...,http://satelite.cptec.inpe.br/repositoriogoes/...,2023-05-20 12:00:00.000,0,SBCT,...,2023-05-20 13:00:00.000,SBCT,SBSPSBCT,-25.414480,-48.597751,143.0,295.0,2022-06-10 10:58:05,-3,2023-05-20 13:32:06
12672,c3c8b46a8d4c0a09565b1c61a475d2d9,SBSP,SBCT,2023-05-20 13:35:06,2023-05-20 13:00:00.000,MULTIPOINT ((-0.8911832312799806 -0.5097777857...,http://satelite.cptec.inpe.br/repositoriogoes/...,2023-05-20 12:00:00.000,0,SBCT,...,2023-05-20 13:00:00.000,SBCT,SBSPSBCT,-23.581591,-46.721669,57.0,211.0,2022-06-10 10:31:04,-3,2023-05-20 13:32:06

In [ ]:
test[["flightid", "linha", "lat", "lon", "flightlevel", "speed", "dt_dep", "dt_radar"]].to_csv("data/test_cat62.csv", index=False)

In [20]:
import pandas as pd
test = pd.read_csv("data/idsc_dataset.csv", sep=";")

In [ ]:
#filtered_cat62.to_csv("data/test_cat62.csv", index=False)

In [16]:
test

,flightid,origem,destino,hora_ref,dt_dep,snapshot_radar,path,hora_esperas,esperas,aero_esperas,...,metaf,aero_metaf,hora_metar,metar,aero_metar,hora_tcp,troca,aero_tcp,hora_tcr,aero_tcr
0,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,11:53:30,MULTIPOINT ((-0.9862962481402141 -0.2329259019...,http://satelite.cptec.inpe.br/repositoriogoes/...,10:00:00,1,SBSP,...,METAF SBSP 211100Z 32007KT 9999 SCT033 ...,SBSP,10:00:00,METAR SBSP 211000Z 34007KT 290V010 CAVOK 18/13...,SBSP,11:00:00,0.0,SBSP,NaN,NaN
1,865dbbbe74bebea18a71f24342516ff0,SBSP,SBCT,00:00:00,00:04:37,MULTIPOINT ((-0.8863534722346053 -0.5093356150...,http://satelite.cptec.inpe.br/repositoriogoes/...,23:00:00,0,SBCT,...,METAF SBCT 150000Z 11008KT 1000 BR OVC033...,SBCT,23:00:00,METAR SBCT 142300Z 13005KT 100V200 CAVOK 11/06...,SBCT,00:00:00,0.0,SBCT,23:00:00,SBCT
2,1803af9cfc6a2c74d188481e3ffd848e,SBGR,SBPA,01:00:00,01:33:15,MULTIPOINT ((-0.8966138193125871 -0.5115119601...,http://satelite.cptec.inpe.br/repositoriogoes/...,00:00:00,0,SBPA,...,METAF SBPA 030100Z 08005KT 9999 SCT011 ...,SBPA,00:00:00,METAR SBPA 030000Z 07004KT 030V090 9000 NSC 21...,SBPA,01:00:00,0.0,SBPA,NaN,NaN
3,f6af733a687f904183efd149ec713be5,SBCT,SBSV,03:00:00,03:54:14,MULTIPOINT ((-0.8586718860112791 -0.4418648049...,http://satelite.cptec.inpe.br/repositoriogoes/...,02:00:00,0,SBSV,...,NaN,NaN,02:00:00,METAR SBSV 150200Z 06009KT 9999 SCT020 25/22 Q...,SBSV,03:00:00,0.0,SBSV,02:00:00,SBSV
4,6117f9ac60b7f66b740c9130be433313,SBRJ,SBGR,00:00:00,00:27:32,MULTIPOINT ((-0.8914635585346382 -0.5234904405...,http://satelite.cptec.inpe.br/repositoriogoes/...,23:00:00,0,SBGR,...,METAF SBGR 230000Z 32008KT CAVOK 24/04 Q1010=\n,SBGR,23:00:00,METAR COR SBGR 222300Z 06004KT CAVOK 23/08 Q1013=,SBGR,00:00:00,0.0,SBGR,23:00:00,SBGR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40034,4e08052066073297c7a3c55798618324,SBSV,SBRF,20:00:00,20:25:00,MULTIPOINT ((-0.8955415064673201 -0.5234137952...,http://satelite.cptec.inpe.br/repositoriogoes/...,19:00:00,0,SBRF,...,NaN,NaN,19:00:00,METAR SBRF 181900Z 19015KT 9999 SCT023 BKN060 ...,SBRF,20:00:00,0.0,SBRF,NaN,NaN
40035,e22f120c65f5759aa8df576b59d71be3,SBCT,SBSP,08:00:00,08:50:22,MULTIPOINT ((-0.8903194203987348 -0.5144905777...,http://satelite.cptec.inpe.br/repositoriogoes/...,07:00:00,0,SBSP,...,METAF SBSP 090800Z 36003KT CAVOK 19/10 Q1017=\n,SBSP,07:00:00,METAR SBSP 090700Z AUTO VRB02KT CAVOK 19/17 Q1...,SBSP,08:00:00,0.0,SBSP,NaN,NaN
40036,ca9399162037201a4d0c49c832a32739,SBGR,SBCF,11:00:00,11:30:03,MULTIPOINT ((-0.8963144777278773 -0.5234059876...,http://satelite.cptec.inpe.br/repositoriogoes/...,10:00:00,0,SBCF,...,METAF SBCF 221100Z 13004KT CAVOK 21/09 Q1016=\n,SBCF,10:00:00,METAR SBCF 221000Z 16003KT 9000 NSC 13/12 Q1018=,SBCF,11:00:00,0.0,SBCF,NaN,NaN
40037,560136088f5f1493dbad809a3554172c,SBBR,SBGR,12:00:00,12:25:21,NaN,http://satelite.cptec.inpe.br/repositoriogoes/...,11:00:00,0,SBGR,...,METAF SBGR 231200Z 34010KT CAVOK 25/07 Q1012=\n,SBGR,11:00:00,METAR SBGR 231100Z 03004KT CAVOK 25/10 Q1014=,SBGR,12:00:00,0.0,SBGR,NaN,NaN
40038,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,00:59:07,MULTIPOINT ((-0.8995693853177327 -0.4320829335...,http://satelite.cptec.inpe.br/repositoriogoes/...,23:00:00,0,SBPA,...,METAF SBPA 050000Z 20006KT 2000 BR OVC033...,SBPA,23:00:00,METAR SBPA 042300Z VRB02KT 8000 OVC009 17/16 Q...,SBPA,00:00:00,0.0,SBPA,NaN,NaN

In [21]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, first, to_date, unix_timestamp
from pyspark.sql.window import Window

spark = SparkSession.builder.config("spark.driver.memory", "15g").appName("Dataframe Example").getOrCreate()

cat62 = spark.read.csv('data/cat62.csv', header=True)

bimtra = spark.read.csv('data/bimtra.csv', header=True)
bimtra = bimtra.withColumn("linha", bimtra["origem"] + bimtra["destino"])
bimtra = bimtra.groupBy("flightid").agg(first("linha").alias("linha"))
bimtra = bimtra.select("*")
bimtra = bimtra.drop("linha")
cat62 = cat62.join(bimtra, "flightid", "left_outer")

normal_routes = spark.read.csv('data/normal_routes.csv', header=True)
cat62_filtered = cat62.join(normal_routes, cat62.flightid == normal_routes.flightid, how='inner')

test = spark.createDataFrame(test[["flightid", "origem", "destino", "hora_ref", "path", "dt_dep"]])

/home/bruno/.local/lib/python3.10/site-packages/pyspark/sql/pandas/conversion.py:485: FutureWarning: is_datetime64tz_dtype is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.DatetimeTZDtype)` instead.
  if should_localize and is_datetime64tz_dtype(s.dtype) and s.dt.tz is not None:

In [19]:
test.show()

23/10/05 21:16:52 WARN TaskSetManager: Stage 43 contains a task of very large size (22557 KiB). The maximum recommended task size is 1000 KiB.

+--------------------+------+-------+--------+--------+--------------------+--------------------+------------+-------+------------+----------+--------------------+----------+----------+--------------------+----------+--------+-----+--------+--------+--------+
|            flightid|origem|destino|hora_ref|  dt_dep|      snapshot_radar|                path|hora_esperas|esperas|aero_esperas|hora_metaf|               metaf|aero_metaf|hora_metar|               metar|aero_metar|hora_tcp|troca|aero_tcp|hora_tcr|aero_tcr|
+--------------------+------+-------+--------+--------+--------------------+--------------------+------------+-------+------------+----------+--------------------+----------+----------+--------------------+----------+--------+-----+--------+--------+--------+
|4f0356600f61e3fcb...|  SBBR|   SBSP|11:00:00|11:53:30|MULTIPOINT ((-0.9...|http://satelite.c...|    10:00:00|      1|        SBSP|  11:00:00|METAF SBSP 211100...|      SBSP|  10:00:00|METAR SBSP 211000...|      SBSP|11:00:00|  0.0|    SBSP|     NaN|     NaN|
|865dbbbe74bebea18...|  SBSP|   SBCT|00:00:00|00:04:37|MULTIPOINT ((-0.8...|http://satelite.c...|    23:00:00|      0|        SBCT|  00:00:00|METAF SBCT 150000...|      SBCT|  23:00:00|METAR SBCT 142300...|      SBCT|00:00:00|  0.0|    SBCT|23:00:00|    SBCT|
|1803af9cfc6a2c74d...|  SBGR|   SBPA|01:00:00|01:33:15|MULTIPOINT ((-0.8...|http://satelite.c...|    00:00:00|      0|        SBPA|  01:00:00|METAF SBPA 030100...|      SBPA|  00:00:00|METAR SBPA 030000...|      SBPA|01:00:00|  0.0|    SBPA|     NaN|     NaN|
|f6af733a687f90418...|  SBCT|   SBSV|03:00:00|03:54:14|MULTIPOINT ((-0.8...|http://satelite.c...|    02:00:00|      0|        SBSV|       NaN|                 NaN|       NaN|  02:00:00|METAR SBSV 150200...|      SBSV|03:00:00|  0.0|    SBSV|02:00:00|    SBSV|
|6117f9ac60b7f66b7...|  SBRJ|   SBGR|00:00:00|00:27:32|MULTIPOINT ((-0.8...|http://satelite.c...|    23:00:00|      0|        SBGR|  00:00:00|METAF SBGR 230000...|      SBGR|  23:00:00|METAR COR SBGR 22...|      SBGR|00:00:00|  0.0|    SBGR|23:00:00|    SBGR|
|f38e70bf6cbea10dd...|  SBCF|   SBSV|09:00:00|09:10:47|MULTIPOINT ((-0.8...|http://satelite.c...|    08:00:00|      0|        SBSV|       NaN|                 NaN|       NaN|  08:00:00|METAR SBSV 130800...|      SBSV|09:00:00|  0.0|    SBSV|     NaN|     NaN|
|26d9687c376fc00f5...|  SBSP|   SBCF|09:00:00|09:25:42|MULTIPOINT ((-0.8...|http://satelite.c...|    08:00:00|      0|        SBCF|  09:00:00|METAF SBCF 210900...|      SBCF|  08:00:00|METAR SBCF 210800...|      SBCF|09:00:00|  0.0|    SBCF|08:00:00|    SBCF|
|ca61361d356c68e22...|  SBSV|   SBSP|13:00:00|13:28:46|                 NaN|http://satelite.c...|    12:00:00|      0|        SBSP|  13:00:00|METAF SBSP 111300...|      SBSP|  12:00:00|METAR SBSP 111200...|      SBSP|13:00:00|  0.0|    SBSP|     NaN|     NaN|
|72301f4a63689438a...|  SBPA|   SBBR|20:00:00|20:48:02|MULTIPOINT ((-0.8...|http://satelite.c...|    19:00:00|      0|        SBBR|  20:00:00|METAF SBBR 132000...|      SBBR|  19:00:00|METAR SBBR 131900...|      SBBR|20:00:00|  0.0|    SBBR|     NaN|     NaN|
|532c4932b33905129...|  SBCF|   SBRF|22:00:00|22:16:40|MULTIPOINT ((-0.8...|http://satelite.c...|    21:00:00|      0|        SBRF|       NaN|                 NaN|       NaN|  21:00:00|METAR SBRF 012100...|      SBRF|22:00:00|  0.0|    SBRF|     NaN|     NaN|
|789c7ee47309c46de...|  SBSP|   SBRJ|13:00:00|13:24:44|                 NaN|http://satelite.c...|    12:00:00|      0|        SBRJ|  13:00:00|METAF SBRJ 161300...|      SBRJ|  12:00:00|METAR SBRJ 161200...|      SBRJ|13:00:00|  0.0|    SBRJ|12:00:00|    SBRJ|
|2537c20e7dfea4cb2...|  SBGL|   SBGR|23:00:00|23:25:41|MULTIPOINT ((-0.8...|http://satelite.c...|    22:00:00|      0|        SBGR|  23:00:00|METAF SBGR 302300...|      SBGR|  22:00:00|METAR SBGR 302200...|      SBGR|23:00:00|  0.0|    SBGR|     NaN|     NaN|
|51a26098b61a768d5...|  SBRF|   SBSP|06:00:00|06:05:58|MULTIPOINT ((-0.6...|http://satelite.c...|    05:00:00|      0|        SBSP|  06:00:00|METAF SBSP 290600...|      SBSP|  05:00:00|METAR SBSP 290500...|      SBSP|06:00:00|  0.0|    SBSP|     NaN|     NaN|
|d3a3c7c254dd51872...|  SBGL|   SBGR|22:00:00|22:00:15|MULTIPOINT ((-0.8...|http://satelite.c...|    21:00:00|      0|        SBGR|  22:00:00|METAF SBGR 292200...|      SBGR|  21:00:00|METAR SBGR 292100...|      SBGR|22:00:00|  0.0|    SBGR|     NaN|     NaN|
|a3d5202525918cf2c...|  SBGR|   SBGL|23:00:00|23:38:09|MULTIPOINT ((-0.8...|http://satelite.c...|    22:00:00|      0|        SBGL|  23:00:00|METAF SBGL 222300...|      SBGL|  22:00:00|METAR SBGL 222200...|      SBGL|23:00:00|  0.0|    SBGL|     NaN|     NaN|
|6b7ac0692df6929ef...|  SBCF|   SBSP|11:00:00|11:26:40|MULTIPOINT ((-0.8...|http://satelite.c...|    10:00:00|      0|        SBSP|  11:00:00|METAF SBSP 111100...|      SBSP|  10:00:00|METAR SBSP 111000...|      SBSP|11:00:00|  0.0|    SBSP|     NaN|     NaN|
|04d94ea3e1ab99243...|  SBPA|   SBCT|19:00:00|19:06:06|MULTIPOINT ((-0.8...|http://satelite.c...|    18:00:00|      0|        SBCT|  19:00:00|METAF SBCT 151900...|      SBCT|  18:00:00|METAR SBCT 151800...|      SBCT|19:00:00|  0.0|    SBCT|18:00:00|    SBCT|
|a11dc44b16fc66de9...|  SBPA|   SBSP|11:00:00|11:03:07|                 NaN|http://satelite.c...|    10:00:00|      0|        SBSP|  11:00:00|METAF SBSP 151100...|      SBSP|  10:00:00|METAR SBSP 151000...|      SBSP|11:00:00|  0.0|    SBSP|     NaN|     NaN|
|b5916d50b537379f6...|  SBGR|   SBSV|17:00:00|17:14:14|MULTIPOINT ((-0.8...|http://satelite.c...|    16:00:00|      0|        SBSV|       NaN|                 NaN|       NaN|  16:00:00|METAR SBSV 201600...|      SBSV|17:00:00|  0.0|    SBSV|     NaN|     NaN|
|ca75b5ec5e9afb403...|  SBCT|   SBRJ|20:00:00|20:33:45|MULTIPOINT ((-0.8...|http://satelite.c...|    19:00:00|      0|        SBRJ|  20:00:00|METAF SBRJ 312000...|      SBRJ|  19:00:00|METAR SBRJ 311900...|      SBRJ|20:00:00|  0.0|    SBRJ|19:00:00|    SBRJ|
+--------------------+------+-------+--------+--------+--------------------+--------------------+------------+-------+------------+----------+--------------------+----------+----------+--------------------+----------+--------+-----+--------+--------+--------+
only showing top 20 rows

In [22]:
test = test.withColumn("linha_test", test["origem"] + test["destino"])

cat62_filtered = cat62_filtered.drop("flightid")

test = test.join(cat62_filtered, test.linha_test == cat62_filtered.linha, "left")

In [23]:
test = test.drop('linha_test') 
test = test.withColumn("dt_radar", (col("dt_radar") / 1000).cast("timestamp"))
test = test.withColumn("dt_dep", to_date(unix_timestamp(col('dt_dep'), 'yyyy-MM-dd').cast("timestamp")))

test = test.orderBy("flightid", "dt_radar")

window = Window.partitionBy('flightid').orderBy('dt_radar')
first_route_event = test.select('flightid', first('dt_radar').over(window).alias('first_dt_radar'))

test = test.join(first_route_event, on='flightid', how="left")

#test.write.csv('data/test_cat62_v3.csv', header=True)
#
#test.show()

In [24]:

test = test.toPandas()

/home/bruno/.local/lib/python3.10/site-packages/pyspark/sql/pandas/types.py:563: FutureWarning: is_datetime64tz_dtype is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.DatetimeTZDtype)` instead.
  if not is_datetime64tz_dtype(pser.dtype):
/home/bruno/.local/lib/python3.10/site-packages/pyspark/sql/pandas/types.py:379: FutureWarning: is_datetime64tz_dtype is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.DatetimeTZDtype)` instead.
  if is_datetime64tz_dtype(s.dtype):
/home/bruno/.local/lib/python3.10/site-packages/pyspark/sql/pandas/types.py:563: FutureWarning: is_datetime64tz_dtype is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.DatetimeTZDtype)` instead.
  if not is_datetime64tz_dtype(pser.dtype):
/home/bruno/.local/lib/python3.10/site-packages/pyspark/sql/pandas/types.py:379: FutureWarning: is_datetime64tz_dtype is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.DatetimeTZDtype)` instead.
  if is_datetime64tz_dtype(s.dtype):

In [2]:
import pandas as pd
test = pd.read_csv("data/idsc_dataset.csv", delimiter=";")

In [4]:
test["data"] = pd.to_datetime(test["path"].str.split("/").str[-1].str.split("_", expand=True)[1].str.split(".", expand=True)[0])

In [9]:
test

,flightid,origem,destino,hora_ref,dt_dep,snapshot_radar,path,hora_esperas,esperas,aero_esperas,...,aero_metaf,hora_metar,metar,aero_metar,hora_tcp,troca,aero_tcp,hora_tcr,aero_tcr,data
0,4f0356600f61e3fcbea8ed8a137a2423,SBBR,SBSP,11:00:00,11:53:30,MULTIPOINT ((-0.9862962481402141 -0.2329259019...,http://satelite.cptec.inpe.br/repositoriogoes/...,10:00:00,1,SBSP,...,SBSP,10:00:00,METAR SBSP 211000Z 34007KT 290V010 CAVOK 18/13...,SBSP,11:00:00,0.0,SBSP,NaN,NaN,2023-08-21 11:00:00
1,865dbbbe74bebea18a71f24342516ff0,SBSP,SBCT,00:00:00,00:04:37,MULTIPOINT ((-0.8863534722346053 -0.5093356150...,http://satelite.cptec.inpe.br/repositoriogoes/...,23:00:00,0,SBCT,...,SBCT,23:00:00,METAR SBCT 142300Z 13005KT 100V200 CAVOK 11/06...,SBCT,00:00:00,0.0,SBCT,23:00:00,SBCT,2023-09-15 00:00:00
2,1803af9cfc6a2c74d188481e3ffd848e,SBGR,SBPA,01:00:00,01:33:15,MULTIPOINT ((-0.8966138193125871 -0.5115119601...,http://satelite.cptec.inpe.br/repositoriogoes/...,00:00:00,0,SBPA,...,SBPA,00:00:00,METAR SBPA 030000Z 07004KT 030V090 9000 NSC 21...,SBPA,01:00:00,0.0,SBPA,NaN,NaN,2023-09-03 01:00:00
3,f6af733a687f904183efd149ec713be5,SBCT,SBSV,03:00:00,03:54:14,MULTIPOINT ((-0.8586718860112791 -0.4418648049...,http://satelite.cptec.inpe.br/repositoriogoes/...,02:00:00,0,SBSV,...,NaN,02:00:00,METAR SBSV 150200Z 06009KT 9999 SCT020 25/22 Q...,SBSV,03:00:00,0.0,SBSV,02:00:00,SBSV,2023-09-15 03:00:00
4,6117f9ac60b7f66b740c9130be433313,SBRJ,SBGR,00:00:00,00:27:32,MULTIPOINT ((-0.8914635585346382 -0.5234904405...,http://satelite.cptec.inpe.br/repositoriogoes/...,23:00:00,0,SBGR,...,SBGR,23:00:00,METAR COR SBGR 222300Z 06004KT CAVOK 23/08 Q1013=,SBGR,00:00:00,0.0,SBGR,23:00:00,SBGR,2023-08-23 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40034,4e08052066073297c7a3c55798618324,SBSV,SBRF,20:00:00,20:25:00,MULTIPOINT ((-0.8955415064673201 -0.5234137952...,http://satelite.cptec.inpe.br/repositoriogoes/...,19:00:00,0,SBRF,...,NaN,19:00:00,METAR SBRF 181900Z 19015KT 9999 SCT023 BKN060 ...,SBRF,20:00:00,0.0,SBRF,NaN,NaN,2023-09-18 20:00:00
40035,e22f120c65f5759aa8df576b59d71be3,SBCT,SBSP,08:00:00,08:50:22,MULTIPOINT ((-0.8903194203987348 -0.5144905777...,http://satelite.cptec.inpe.br/repositoriogoes/...,07:00:00,0,SBSP,...,SBSP,07:00:00,METAR SBSP 090700Z AUTO VRB02KT CAVOK 19/17 Q1...,SBSP,08:00:00,0.0,SBSP,NaN,NaN,2023-09-09 08:00:00
40036,ca9399162037201a4d0c49c832a32739,SBGR,SBCF,11:00:00,11:30:03,MULTIPOINT ((-0.8963144777278773 -0.5234059876...,http://satelite.cptec.inpe.br/repositoriogoes/...,10:00:00,0,SBCF,...,SBCF,10:00:00,METAR SBCF 221000Z 16003KT 9000 NSC 13/12 Q1018=,SBCF,11:00:00,0.0,SBCF,NaN,NaN,2023-08-22 11:00:00
40037,560136088f5f1493dbad809a3554172c,SBBR,SBGR,12:00:00,12:25:21,NaN,http://satelite.cptec.inpe.br/repositoriogoes/...,11:00:00,0,SBGR,...,SBGR,11:00:00,METAR SBGR 231100Z 03004KT CAVOK 25/10 Q1014=,SBGR,12:00:00,0.0,SBGR,NaN,NaN,2023-08-23 12:00:00
40038,007ff2faa56e24e8422a07f1fe1d116a,SBGR,SBPA,00:00:00,00:59:07,MULTIPOINT ((-0.8995693853177327 -0.4320829335...,http://satelite.cptec.inpe.br/repositoriogoes/...,23:00:00,0,SBPA,...,SBPA,23:00:00,METAR SBPA 042300Z VRB02KT 8000 OVC009 17/16 Q...,SBPA,00:00:00,0.0,SBPA,NaN,NaN,2023-09-05 00:00:00

In [10]:
metar = test.groupby(["aero_metar", "data"])["metar"].first()

In [12]:
metar = pd.DataFrame(metar).reset_index()
metar.to_csv("data/test_metar.csv", index=False)

In [13]:
metaf = test.groupby(["aero_metaf", "data"])["metaf"].first()

In [14]:
metaf = pd.DataFrame(metaf).reset_index()
metaf.to_csv("data/test_metaf.csv", index=False)